### ISSUE TITLE
[3D particle emitter] particle objects always produce 1 particle at coords 0;0 on creation

### ISSUE THREAD

**Issue by CLEDU007** [GDevelopApp/GDevelop-extensions#1019]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/GDevelopApp/GDevelop-extensions/issues)

### Enter the name of the extension

3D particle emitter

### Describe the bug of the extension

3D particle emitter objects created using events spawn one particle at coords 0;0 before producing them at the emitter's position

### Steps to reproduce

1. Use action "create object [name of the 3D particle emitter]" and set position different than x=0 and y=0
2. start preview
3. point camera at 0;0
4. see 1 particle being emitted every time the action "create object [name of the 3D particle emitter]" is executed

### GDevelop platform

Desktop

### GDevelop version

5.2.172

### Platform info

Windows 10 Pro

**Comment by D8H** [comment]
Thanks for reporting an issue. I know this problem but it doesn't look trivial to fix. I'll come back to it.
