### ISSUE TITLE
Error: THREE not defined using WithThreeJS Extension

### ISSUE THREAD

**Issue by TornadoTheCowGaming** [GDevelopApp/GDevelop-extensions#1192]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/GDevelopApp/GDevelop-extensions/issues)

### Enter the name of the extension

WithThreeJS

### Describe the bug of the extension

I am Making a 3D first person horror game in Gdevelop, and I installed the Latest version of "WithThreeJS" into The latest Version of Gdevelop to Make the "3D" part as said in the YT tutorial. After I installed it I Entered "Create 3D Scene" Command into the Project Events tab. When I clicked "Preview" the screen was black, With a red Warning Error message Saying "THREE was not defined" The guy in the video clicked it and it came up with A 3d view of his Top down Platformer, Like mine should of, as I followed his tutorial EXACTLY and the video was made recently. I searched up how to fix but it was all JS coders not anything Gdevelop. How to fix? Picture of Error Below VVVVVVV
![Screenshot 2024-03-02 213504](https://github.com/GDevelopApp/GDevelop-extensions/assets/161922957/fcc97516-4911-4d3d-9249-af94cb2b0674)

### Steps to reproduce

1. Open Gdevelop Latest version and Create a Backround with a Player with Top down movement. 2. Open Mannage Project and Click Create/Open Extension, Then toggle Community Extensions and Find and Install the "WithThreeJS" Extension. 3. Enter the "Create 3D Scene" command into the Project events tab set to happen at the Beggining of the Scene. 4. Click "Preview" and it Should be all black with an Error message saying "JavaScript Error: THREE was not defined" at least it does for me And I'm using the latest version of the Extension and Gdevelop.
![Screenshot 2024-03-02 213504](https://github.com/GDevelopApp/GDevelop-extensions/assets/161922957/c37cc21e-6bca-49cc-bb9e-dddc77f45afe)

### GDevelop platform

Desktop

### GDevelop version

5.3.192

### Platform info

<details>

*OS (Windows)*
>

*OS Version (Windows 11)
</details>

### Additional context

This Error Makes With3JS Extension Unusable, which is unfortunate as it's really cool.

**Comment by PANDAKO-GitHub** [comment]
Thanks for the feedback.
The solution to that problem is described on the following page.
https://pandako.itch.io/with-threejs-extension-for-gdevelop/devlog/631434/about-the-warning-please-add-an-enable-withthreejs-object-to-a-scene

I have confirmed the issue where no warning is displayed.

**Comment by TornadoTheCowGaming** [comment]
> Thanks for the feedback. The solution to that problem is described on the following page. https://pandako.itch.io/with-threejs-extension-for-gdevelop/devlog/631434/about-the-warning-please-add-an-enable-withthreejs-object-to-a-scene
> 
> I have confirmed the issue where no warning is displayed.

Thank you so much!
