### ISSUE TITLE
FireBullet extension ammo quantity goes below zero if the ammo quantity is set to a non-whole number,

### ISSUE THREAD

**Issue by doug13579** [GDevelopApp/GDevelop-extensions#1250]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/GDevelopApp/GDevelop-extensions/issues)

### Enter the name of the extension

FireBullet version .6.4.0

### Describe the bug of the extension

If the ammo quantity is set to a non-whole number, it doesn't stop shooting at 0, the ammo quantity goes into the negative. I'm guessing it's checking if something equals zero instead of less than or equal to zero. A fix would be to either use <= or change the ammo quantity to a whole number when it's set.

![ScreenRecorderProject22_2](https://github.com/GDevelopApp/GDevelop-extensions/assets/113511006/4c15224d-28c5-4961-b758-06bbbb8f80f7)

### Steps to reproduce

Set the ammo quantity to a non-whole number like 10.5 and shoot.
This happened because someone was setting the ammo based on a difficulty ratio instead of a specific number.
![image](https://github.com/GDevelopApp/GDevelop-extensions/assets/113511006/dd8a567a-74a2-4599-a1f7-362d09837443)

I fixed it by using trunc()
![image](https://github.com/GDevelopApp/GDevelop-extensions/assets/113511006/705345e1-2256-40ae-8f97-5ba907056b12)

### GDevelop platform

Desktop

### GDevelop version

5.3.198

### Platform info

windows 10

**Comment by tristanbob** [comment]
Thanks for reporting this.  I will look into it.

**Comment by tristanbob** [comment]
This is fixed by #1256
