### ISSUE TITLE
[Mouse Pointer Lock] Latest versions do not work reliably on Linux/Brave/Chrome

### ISSUE THREAD

**Issue by Skrownerve** [GDevelopApp/GDevelop-extensions#1288]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/GDevelopApp/GDevelop-extensions/issues)

### Enter the name of the extension

Mouse Pointer Lock

### Describe the bug of the extension

Certain 0.1.4 versions and all newer versions up to 0.1.6 do not work reliably for me when testing games in engine, using the AppImage version of GDevelop on Linux. Clicking does not lock the cursor. It has worked maybe 5% of the time when I test the game. LehaM in Discord reports that it does not work in Brave or Chrome browsers, but Firefox works fine.

### Steps to reproduce

1. Install MousePointerLock
2. Set up event to request lock when left mouse button released
3. Preview game
4. Click - the mouse is not locked

### GDevelop platform

Desktop

### GDevelop version

5.3.201

### Platform info

<details>

*OS (e.g. Windows, Linux, macOS, Android, iOS)*
>

*OS Version (e.g. Windows 10, macOS 10.15)*
>

*Browser(For Web) (e.g. Chrome, Firefox, Safari)*
>

*Device(For Mobile) (e.g. iPhone 12, Samsung Galaxy S21)*
>

</details>

**Comment by 4ian** [comment]
Should be fixed by https://github.com/GDevelopApp/GDevelop-extensions/pull/1385
