### ISSUE TITLE
Change Amount of Jumps (Platformer, Mid-Air)

### ISSUE THREAD

**Issue by Elairyx7301** [GDevelopApp/GDevelop-extensions#142]
## Describe the extension
With this extension, you can freely change the amount of jumps a Platformer Character can perform mid-air. You can bind your own key to it and you have the option to only apply changes when touching the ground or to instantly force the change. This extension that makes limiting mid-air jumps very easy to set up should make creating and allowing double-jumps simple and intuitive.

Note that when setting the amount of allowed jumps to for example 2, the player will be able to jump a total of 3 times. Once off the ground and then the entered 2 additional jumps mid-air.

## Checklist

- [x] Extension has a proper name and description.
- [x] Extension has tags (for example: "platform, brick, breakable").
- [x] All behaviors have a description.
- [x] All functions (actions, conditions, expressions) have descriptions and proper sentences.
- [x] I confirm that this extension can be intergrated to this GitHub repository, distributed and MIT licensed.
- [x] I've followed the best practices listed on http://wiki.compilgames.net/doku.php/gdevelop5/extensions/best-practices

## Extension game example
[Change Jumps Example.zip](https://github.com/4ian/GDevelop-extensions/files/6472650/Change.Jumps.Example.zip)

## Extension file
The .json file can be found inside the following .zip folder:
[JumpMidAir.zip](https://github.com/4ian/GDevelop-extensions/files/6447478/JumpMidAir.zip)

**Comment by ElairyxOfficial** [comment]
Hello D8H,
I have updated the extension title and added a game example.
Thanks for letting me know.

**Comment by D8H** [comment]
I feel like it should be a behavior instead of an action.

**Comment by ElairyxOfficial** [comment]
But it needs the platformer behavior for it. I thought about it as an extension or add-on to the platformer. Making this a separate behavor would require me to copy the entire platformer because of the platform collisions, jump speed, gravity etc, right?

**Comment by D8H** [comment]
Sorry, You're right. Behaviors can't ask their object to have another behavior. It didn't occur to me.

**Comment by tristanbob** [comment]
> Sorry, you're right. Behaviors can't ask their object to have another behavior. It didn't occur to me.

This is something that needs to be submitted as a feature request.  I am often forced to use Action functions because I require specific behaviors of objects.

**Comment by 4ian** [comment]
This is indeed something that is a feature request, called "Behavior composition": https://trello.com/c/U8hR6L7l/392-allow-behaviors-to-be-configured-to-work-with-other-behaviors-behavior-composition
And we can imagine that if you select a behavior that requires other behaviors, and that they don't exist on the object, they can be added automatically :)

**Comment by D8H** [comment]
The coyote time time will also requires a PlatformerObject.
https://github.com/GDevelopApp/GDevelop-extensions/issues/193

I think that they should be tested together, because they may conflict each other. For instance, an air jump can happen during a coyote time and should not be counted by the multi-jump behavior.

Maybe, they will have to be merged in one behavior like "Jump enhancement".

**Comment by D8H** [comment]
Hello Elairyx, since the beta 117, it's possible to make this extension. You can require a Platformer Character using a behavior property.

**Comment by Elairyx7301** [comment]
Thank you for the reminder! I'll take another look at the files soon.

**Comment by D8H** [comment]
Please, try to integrate your features in this extension when the PR is merged:
* https://github.com/GDevelopApp/GDevelop-extensions/pull/255

**Comment by D8H** [comment]
The "Advanced Jump" extension was added to the repository. Please, try to add your features on it. Feel free to "at" me in Discord if you have any question.

**Comment by Elairyx7301** [comment]
This version of the extension is outdated. The newest and most stable version is currently merged in #255

**Comment by 4ian** [comment]
I'm closing this then :)
