### ISSUE TITLE
Iframe extension

### ISSUE THREAD

**Issue by DHsoftw** [GDevelopApp/GDevelop-extensions#165]
## Simple extension to insert an iframe easily on Gdevelop.
There are people who need to embed websites and thanks to this extension the integration process will be relatively simpler.

## Checklist

- [x] Extension has a proper name and description.
- [x] Extension has tags (for example: "platform, brick, breakable").
- [x] All behaviors have a description.
- [x] All functions (actions, conditions, expressions) have descriptions.
- [x] I confirm that this extension can be intergrated to this GitHub repository, distributed and MIT licensed.

## Extension file

Finally, attach the .json file of your extension here.
[Iframe (new version).zip](https://github.com/4ian/GDevelop-extensions/files/6701414/Iframe.new.version.zip)

**Comment by jack-ii** [comment]
**I updated the extension a bit**
create and delete more than one iframe 
border and scrolling as yes/no button
no longer necessary to type "px"
edited descriptions, labels and parameters to match with GD
[Iframe.zip](https://github.com/4ian/GDevelop-extensions/files/6682880/Iframe.zip)

**Comment by DHsoftw** [comment]
> **I updated the extension a bit**
> create and delete more than one iframe
> border and scrolling as yes/no button
> no longer necessary to type "px"
> edited descriptions, labels and parameters to match with GD
> [Iframe.zip](https://github.com/4ian/GDevelop-extensions/files/6682880/Iframe.zip)

Thanks!
A lot better now.

But it freezes and you cant interact with the website

**Comment by DHsoftw** [comment]
Problem solved adding the repeat event once

**Comment by Bouh** [comment]
I've fixed errors and now it fit to the best pratices.

[iframe_extension.zip](https://github.com/GDevelopApp/GDevelop-extensions/files/6797697/iframe_extension.zip)

**Comment by DHsoftw** [comment]
But which errors? It already works correctly

> I've fixed errors and now it fit to the best pratices.
> 
> [iframe_extension.zip](https://github.com/GDevelopApp/GDevelop-extensions/files/6797697/iframe_extension.zip)

**Comment by Bouh** [comment]
> But which errors? It already works correctly
> 
> >

yes it worked, just fixed:
- Typo in desciptions
- Version number
- camelCase in functions and arguments

Still don't know if we should accept the extensions that affect the DOM.
Also the iframe have a static size and canno't be resized related to the window size, this is something I would like to see before I give my approval.

**Comment by arthuro555** [comment]
> Still don't know if we should accept the extensions that affect the DOM.

4ian said [it is fine to add extensions that use the DOM, but that they should use a special tag](http://wiki.compilgames.net/doku.php/gdevelop5/extensions/best-practices#no_usage_of_dom_elements_if_you_do_use_a_specific_tag).

**Comment by DHsoftw** [comment]
> Also the iframe have a static size and cannot be resized related to the window size

You can add a formula in the gdevelop event so that it appears as determined in a variable or according to the screen size

**Comment by DHsoftw** [comment]
Also I have tested the extension on browser, mobile phones (android, with default cordova on click exportation), desktop app for windows, Linux and Mac. It works correctly on all my devices, but as indicated, the dom tag must be added.
I put the updated file with that tag below:

**Changes:** 

- Added a condition to check if there is any existing iframe
- Added necessary tag

[iframe.zip](https://github.com/GDevelopApp/GDevelop-extensions/files/6811717/iframe.zip)

**Comment by arthuro555** [comment]
This extension is frankly a mess. First thing I see opening it:
![image](https://user-images.githubusercontent.com/19349038/125543202-b55546b3-0e2e-469f-93c7-48117fedc9e9.png)
No [pascal case](http://wiki.compilgames.net/doku.php/gdevelop5/extensions/best-practices#action_and_conditions), one condition has no name. 
![image](https://user-images.githubusercontent.com/19349038/125543368-9d8968e3-280e-4406-bb27-77e7f449cd2b.png)
Number variables used with string actions, [variable names that break all best practices](http://wiki.compilgames.net/doku.php/gdevelop5/extensions/best-practices#variables), the variable naming is inconsistent, the condition doesn't have a return value.

Please at least test every condition and action you add, this custom condition would obviously never work as it doesn't even have a return value, and make sure [the best practices](http://wiki.compilgames.net/doku.php/gdevelop5/extensions/best-practices) are respected.

**Comment by DHsoftw** [comment]
I uploaded the wrong file. I have decided to upload the old version with the updated number and label because I lost the changes made earlier (I thought I had exported the latest version)

[iframe.zip](https://github.com/GDevelopApp/GDevelop-extensions/files/6818229/iframe.zip)

**Comment by DHsoftw** [comment]
I have finally decided not to introduce new changes, so this will be the final version

**Comment by Bouh** [comment]
I reviewing this.

**Comment by Bouh** [comment]
Thx for this extension, I've fixed to fit the best practices guide. Added an extra field for CSS.
