### ISSUE TITLE
Explosion Force: Simulate an explosion with physics forces on target objects

### ISSUE THREAD

**Issue by tristanbob** [GDevelopApp/GDevelop-extensions#169]
## Describe the extension

Add physics forces to target objects that are inside the explosion radius.   Forces push away from the explosion center and are stronger the closer the object is to the explosion.

Requirements:
- Target Objects must have physics behavior
- The action "Pick all instances" of Target Objects MUST be used directly above this action.

## Extension file

~~[ExplosionForces_Extension_1.0.0.json.zip](https://github.com/4ian/GDevelop-extensions/files/6722411/ExplosionForces_Extension_1.0.0.json.zip)~~

## Project files

[ExplosionForce.zip](https://github.com/4ian/GDevelop-extensions/files/6722410/ExplosionForce.zip)

**Comment by tristanbob** [comment]
## Version 1.2.1

Good news: This extension is ready for review.

Bad news:  The demo game freezes up with large radius and max force values.  For instance, the starting values of radius=250 and maxforce=250 cause this to happen.  It seems to be worse with large values.  Is this a limitation of Box2d or GDevelop?

## Game freezes with large inputs (but why?)
https://games.gdevelop-app.com/game-213f157b-5819-452a-bd80-5022e647663c/index.html

## Extension file

[ExplosionForce_Extension_1.2.1.json.zip](https://github.com/4ian/GDevelop-extensions/files/6781274/ExplosionForce_Extension_1.2.1.json.zip)

## Project files

[ExplosionForce_SourceFiles.zip](https://github.com/4ian/GDevelop-extensions/files/6781276/ExplosionForce_SourceFiles.zip)

## Screenshot of errors

![Screenshot 2021-07-07 212658](https://user-images.githubusercontent.com/8879811/124858933-31ce5580-df6c-11eb-89b0-f2836a58f18f.jpg)
![Screenshot 2021-07-07 212615](https://user-images.githubusercontent.com/8879811/124858934-3266ec00-df6c-11eb-9b53-de4824f2fce4.jpg)

**Comment by arthuro555** [comment]
This is tricky, as you can see, the crash message doesn't tell much, all we know is that it is the C++ code of Box2D, but the issue could come from a bug or limitation in box 2d, from emscripten (the c++ to js compiler) or from GDevelop passing wrong values/values that don't fit the c++ data type. I'm not sure how that last one would be possible as the box2d function only accepts floats and afaik JavaScript numbers are always floats.

**Comment by Midhil457** [comment]
I am afraid to test it with a high radius. But, as a solution, you could set the radius back to an acceptable size if the given value is too big

**Comment by tristanbob** [comment]
> As a solution, you could set the radius back to an acceptable size if the given value is too big. And add a disclaimer in the description of the parameter

I'm not certain what the exact trigger of the problem is.  You can actually use a very high radius (500 pixels) with a lower max force (50).  It is slow, but it doesn't crash.  You can also use a very high force (500) with a smaller radius (150).  

I'm hoping we can find a root cause.  If we cannot solve it, then I might just add a note "If your game freezes during an explosion, try reducing the radius or max force values."

**Comment by Midhil457** [comment]
Hi, here is my review
- I suggest changing the description a bit, the **bold** text are the changes

"Apply **explosion like** physics forces to target objects that are inside the explosion radius.  Forces push away **the target object** from the explosion center and **the force applied** are stronger the closer the target object is to the explosion **center.**  Target objects will be changed to "Dynamic" physics objects. 

Requirements:
- Target Objects must have physics **2.0** behavior
- The action "Pick all instances" of Target Objects MUST be used directly above this action.

Object Variables (Target Objects):
- "__ExplosionForce.Exploded" (boolean)
- "__ExplosionForce.ForceMagnitude" (number)

Tips:
- Start objects as "Static" physics objects so they won't move or fall over until the explosion automatically converts them to "Dynamic".
- Use the "__ExplosionForce.Exploded" object variable to manage objects that were affected by an explosion.  (For instance, start an opacity tween that fades away and deletes the objects.)"
---
- This, I am a bit confused about. `MassCenterX` and `MassCenterY` doesn't seem to do any difference, but it does work. I am not sure if `CenterX` is better

![ExP](https://user-images.githubusercontent.com/73597906/124953178-863c0880-e032-11eb-8754-bb68e50057a4.PNG)

:)

**Comment by Midhil457** [comment]
> > As a solution, you could set the radius back to an acceptable size if the given value is too big. And add a disclaimer in the description of the parameter
> 
> I'm not certain what the exact trigger of the problem is. You can actually use a very high radius (500 pixels) with a lower max force (50). It is slow, but it doesn't crash. You can also use a very high force (500) with a smaller radius (150).
> 
> I'm hoping we can find a root cause. If we cannot solve it, then I might just add a note "If your game freezes during an explosion, try reducing the radius or max force values."

Is it because when a lot of objects are moving really fast, it breaks the physics calculations? Is it something related to the physics engine?

**Comment by tristanbob** [comment]
## Review response

> "Apply **explosion like** physics forces to target objects that are inside the explosion radius. 

Done

> Forces push away **the target object** from the explosion center 

Done

> and **the force applied** are stronger the closer the target object is to the 

Done

> explosion **center.** Target objects will be changed to "Dynamic" physics objects.

Done

> * Target Objects must have physics **2.0** behavior

Users cannot pick the Physics 1.0 behavior anymore, so I don't think this is needed.

> * This, I am a bit confused about. `MassCenterX` and `MassCenterY` doesn't seem to do any difference, but it does work. I am not sure if `CenterX` is better

I was not aware of this expression but I tried it and it seems to work.  I have changed to using it in case a future update adds non-symmetrical physics collision masks, and this expression should act more "naturally".

## Version 1.3.0

- Applied review changes mentioned above
- Fixed a logic bug with how much force was applied.  Instead of reducing force as distance increases, the max force was happening at the max distance.  I added some large indestructible balls to the game example so you can see how distance and force are applied correctly. 

## Play it here

https://games.gdevelop-app.com/game-908c808a-8c8d-41c7-9433-fafb8d8fdd70/index.html

## Project files

[ExplosionForce_ProjectFiles.zip](https://github.com/4ian/GDevelop-extensions/files/6792514/ExplosionForce_ProjectFiles.zip)

## Video

https://user-images.githubusercontent.com/8879811/125104533-b919e700-e09a-11eb-8741-11ec8c20a315.mp4

**Comment by Midhil457** [comment]
Hi, 

- I think the Help URL is supposed to be a link to a wiki page or an explanation of the extension and not a game link. But, I guess they could look at the source and see how it was implemented (But, for that maybe adding it as an example might be better?). Also that link (https://victrisgames.itch.io/extension-explosion-force) gives a 404 page not found error

- Same for the Author, github is better? But, it might not matter

![Handle](https://user-images.githubusercontent.com/73597906/125106896-cb793c80-e0fd-11eb-8cdc-c2240c70dae3.PNG)

:)

**Comment by tristanbob** [comment]
> * I think the Help URL is supposed to be a link to a wiki page or an explanation of the extension and not a game link. But, I guess they could look at the source and see how it was implemented (But, for that maybe adding it as an example might be better?). Also that link (https://victrisgames.itch.io/extension-explosion-force) gives a 404 page not found error

Try it now.  I didn't have the page published yet, but it should be ready now.  
https://victrisgames.itch.io/extension-explosion-force

I agree that a GDevelop controlled site is preferable (such as the wiki) and I am fine with anyone creating one and then changing this extension to point at it.  I point to my demo game with source files included because I don't currently have the drive to create wiki pages or submitting example games.   If anyone is looking for a way to help, perhaps they can help with this.
 
> * Same for the Author, github is better? But, it might not matter

I think the Author info can be anything (within reason) that they want.  Some creators will prefer email, twitter, website, github, etc.

**Comment by Midhil457** [comment]
Makes sense. I didn't find any other issues. I think this can be added now

:)

**Comment by arthuro555** [comment]
The author info can indeed be anything you want, though the help link really should point to documentation, not the extensions homepage.

**Comment by arthuro555** [comment]
I took a look as well, everything looks fine to me. As the link pont to the page of the example, it is fine to keep it as the help page as it can help as a reference. I'll merge it now.

**Comment by arthuro555** [comment]
Added via def522ae4bd4043d22b243843b6e6fcfddc99fde !
