### ISSUE TITLE
Button behavior extention

### ISSUE THREAD

**Issue by mlafefon** [GDevelopApp/GDevelop-extensions#17]
Make a sprite or a  text box to act like a button
once attached to an object in has a mouse hover effect an a click action.
There are also two parameters: the color when clicked and center object on screen.
## Checklist

- [x] Extension has a proper name and description.
- [x] Extension has tags (for example: "platform, brick, breakable").
- [x] All behaviors have a description.
- [x] All functions (actions, conditions, expressions) have descriptions.
- [x] I confirm that this extension can be intergrated to this GitHub repository, distributed and MIT licensed.

## Extension file

Update:
Left Right mouse support
Move 2px object effect

**Update:02/09**
removed: blend mode of button on click
removed: property of mouse down color
added: property for selecting hoover color
fix: bug when releasing the mouse out of the button the button was moving
**Update:21/09 v2.7**
Bug fix
**Update 19/03

 v2.8**
Bug Fix 
V 4.7
Detect the top most button
A lot of changes and bug fix

v5.0
Add possible  to hook to a keyboard
Hide  button on hidden Layer
Adjust button to fit mobile
Now you can chhose action on muse down or mouse up
simulate click click
[ExtensionButton5.0.json.zip](https://github.com/4ian/GDevelop-extensions/files/4465991/ExtensionButton5.0.json.zip)

**Comment by mlafefon** [comment]
Why this extension is not published?
What is missing?

**Comment by Jeje2201** [comment]
I love your extension @mlafefon, but there is a problem, if you use your extension on an object that has an anchor behavior, then the button doesn't stay press if you keep pressing it, it directly go back to idle / normal
Here is an exemple, the x is normal, the ! has anchor behavior
![button click anchor](https://user-images.githubusercontent.com/19387127/114269021-bf011d00-9a04-11eb-94bb-ecf2609c38d9.gif)

**Comment by 4ian** [comment]
That might be not a blocking problem though. I totally forgot about this extension. Might be a good idea to add it now?

**Comment by Jeje2201** [comment]
Welp, Im playing with the extension, an other issue I just found is like if you press the button it goes down, but when you leave the object before releaseing the click, like cancelling it, it doesnt go back up if you're on mobile
(opened the chrome console while previewing the game to try the mobile on desktop)
![button click anchor](https://user-images.githubusercontent.com/19387127/114270902-26bc6580-9a0f-11eb-8677-e4e6548583d7.gif)

**Comment by 4ian** [comment]
Not ideal then yes :/

**Comment by Jeje2201** [comment]
Looked up the code and found out why
![image](https://user-images.githubusercontent.com/19387127/114270960-71d67880-9a0f-11eb-84c2-7b4119aa56da.png)

Here is whithout mobile check
[button_Extension.zip](https://github.com/4ian/GDevelop-extensions/files/6289899/button_Extension.zip)

**Comment by Jeje2201** [comment]
> That might be not a blocking problem though. I totally forgot about this extension. Might be a good idea to add it now?

Yeah, this extension is like a must have as it's like what lots of people try to create on theire own in any kind of game and this extension does the job smoothly

**Comment by Jeje2201** [comment]
Here is the extension with 
- updated version number (5 -> 6)
- removed extra spaces
- removed empty conditon action
- added icon to the extension

[button_Extension.zip](https://github.com/4ian/GDevelop-extensions/files/6289925/button_Extension.zip)

**Comment by Jeje2201** [comment]
There's a parameter that I don't know if it really has a reason to be in the extension, it's to center the object in the middle of the screen
![image](https://user-images.githubusercontent.com/19387127/114271904-05aa4380-9a14-11eb-9939-c6743f5d8898.png)

I opened the json extension to find out where exactly it's used and there's only one place here
![image](https://user-images.githubusercontent.com/19387127/114271918-19ee4080-9a14-11eb-858c-e0a2a22f450d.png)

It doesn't seem that needed in this extension whereas there is already a powerfull extension for positioning an object / text in the middle, top, bottom, etc.. of the screen : https://github.com/4ian/GDevelop-extensions/issues/30

Do I remove it ?

**Comment by 4ian** [comment]
Yes please, let's remove it! Only keep the minimum stuff for making a "button like" object :)

**Comment by mlafefon** [comment]
Hi guys
since you never published my extension I stopped updating it here.
I have already made a 5.1 version with these changes:

- Add the possibility  to hook the button action to  a keyboard
- Hide  button on hidden Layer
- Adjust button to fit mobile
- Now you can choose action on muse down or mouse up
- simulate click 
- typo fix
I will upload it soon
here it is:
[‏‏ExtensionButton5.1.zip](https://github.com/4ian/GDevelop-extensions/files/6290085/ExtensionButton5.1.zip)


Mlafefon

**Comment by Jeje2201** [comment]
@mlafefon 
>Add the possibility to hook the button action to a keyboard
Hide button on hidden Layer
Adjust button to fit mobile
Now you can choose action on muse down or mouse up

All of this was already in the extension I worked on, from your main message that you edited to keep it update

**Comment by Jeje2201** [comment]
>Yes please, let's remove it! Only keep the minimum stuff for making a "button like" object :)

Done ✅

And added a parameter to custom how deep/down the button goes when pressing it
![image](https://user-images.githubusercontent.com/19387127/114275977-f089e080-9a24-11eb-81aa-3c8d6f2215a5.png)

[button_Extension.zip](https://github.com/4ian/GDevelop-extensions/files/6290197/button_Extension.zip)

**Comment by Jeje2201** [comment]
Found out an other issue that is hard to reproduce by the user but still is a thing, on mobile, if you press close to the button but not really on it, it goes up but doesn't feel press, in the red rectangle, the area im talking about, but if try on desktop, all good

![image](https://user-images.githubusercontent.com/19387127/114276081-668e4780-9a25-11eb-9094-cf69fe0f4207.png)

Gif so you can understand 
![button click anchor](https://user-images.githubusercontent.com/19387127/114276210-ee745180-9a25-11eb-8b2a-6718aab8a5f1.gif)

**Comment by arthuro555** [comment]
Hello, sorry for the late feedback. Would it be possible for someone to send in a simple example project showcasing the extension to help make the review process faster please?

> And so instead of moving it down, you just change the animation from 1 to 2, but it does mean that the user need to have 2 sprites, one for the idle and one for the press, idk what's better

🤔 I think 2 animations is best as most people want a button to have a different image when pressed.

**Comment by arthuro555** [comment]
If there are no updates in the next 10 days, I will consider this abandoned and close the issue.

**Comment by GustavoMarciano** [comment]
> Found out an other issue that is hard to reproduce by the user but still is a thing, on mobile, if you press close to the button but not really on it, it goes up but doesn't feel press, in the red rectangle, the area im talking about, but if try on desktop, all good
> 
> ![image](https://user-images.githubusercontent.com/19387127/114276081-668e4780-9a25-11eb-9094-cf69fe0f4207.png)
> 
> Gif so you can understand
> ![button click anchor](https://user-images.githubusercontent.com/19387127/114276210-ee745180-9a25-11eb-8b2a-6718aab8a5f1.gif)
> 
> Edit 1 :
> **Found out why !**
> Let's say when you press the button, it goes down 2 pixel to create this effect of pressing it, well if you press it from the 2 first pixel on top, it goes down 2 pixel and so your mouse is not on it anymore and so it's goes back up directly
> 
> Idk if it's not better to just change the animation of the object instead of moving it down, like 1 sprite of it normal, and an other for the sprite with the effect pressed, like this
> Idle and Press
> ![image](https://user-images.githubusercontent.com/19387127/114276706-19f83b80-9a28-11eb-8b25-61003ff5628f.png)
> 
> And so instead of moving it down, you just change the animation from 1 to 2, but it does mean that the user need to have 2 sprites, one for the idle and one for the press, idk what's better
> 
> Edit 2 :
> I updated the code to give it a try
> Changing the +- of the y to just 1 or 0 for the animation
> ![image](https://user-images.githubusercontent.com/19387127/114277010-9dfef300-9a29-11eb-84ec-fe9213cd4e2d.png)
> 
> To be honest, I personally prefer by changing the animation because
> 
> * It create a cool effect
> * No problem with the y if pressing on top of the button
> * No problem with anchor behavior
> 
> But it does mean that the user need 2 sprites
> Here is an exemple :
> ![button click anchor](https://user-images.githubusercontent.com/19387127/114276981-655f1980-9a29-11eb-99ff-a8016d983a15.gif)
> 
> And by changing this, it does't work with the text, as the text.. well it's a text, so no animation, so we can keep the y change when it's a text and the 2 sprite when it's object ¯_(ツ)_/¯
> 
> Whats your opinion ?

I was thinking, wouldn't the simplest solution be to just remove the Y posistion option?
I use this extension and one of the uses is not needing double sprites which would increase the size of my games.

**Comment by arthuro555** [comment]
Those both statements seem contradictory 🤔 
Anyways, it has been 10 days without feedback from the original author or someone taking over the work, closing the issue now.

**Comment by Jeje2201** [comment]
Yup sorry, lack of time to create a work around, I did some hotfix but nothing serious to make it public and not that user friendly, it work for me, with double sprites, but code is way too bad
