### ISSUE TITLE
Remove The Kongregate Extension from The Extension Library

### ISSUE THREAD

**Issue by Bouh** [GDevelopApp/GDevelop-extensions#181]
## Description
From https://github.com/4ian/GDevelop/issues/2797

Kongregate does not accept games any more, which makes the extension useless. Probably add a gamejolt or newgrounds API extension to GDevelop 5 instead.

- [x] Verification on Kongregate website
- [x] Check how deleted extension act in GDevelop if we try to update it

**Comment by 4ian** [comment]
> Check how deleted extension act in GDevelop if we try to update it

Nothing bad should happen as existing games having it will continue to work, and it will be removed from the list of extensions, so it won't be listed and you can't "update" it.

**Comment by Bouh** [comment]
Close by https://github.com/GDevelopApp/GDevelop-extensions/commit/a7f8ed33c5050d5ae9776bf8e48cc9a2c912485e
