### ISSUE TITLE
Bug fix: ShadowClones version 0.5.3

### ISSUE THREAD

**Issue by tristanbob** [GDevelopApp/GDevelop-extensions#182]
## Describe the bug

Once shadowclones were deleted, they could not be increased.  This is because the DeleteShadowClones function was using the legacy variable "FrameCount" instead of the new "ClonesCreated" variable.

## Version 0.5.3 

- Fixes bug in DeleteShadowClones function by using the correct variable: "ClonesCreated"

## Extension file

[ShadowClonesExtension_0.5.3.json.zip](https://github.com/GDevelopApp/GDevelop-extensions/files/6801922/ShadowClonesExtension_0.5.3.json.zip)

## Test game

https://games.gdevelop-app.com/game-efe2752b-6780-4de9-aa23-465c9b95b4f8/index.html

## Screenshot of events in the test

![Screenshot 2021-07-11 233121](https://user-images.githubusercontent.com/8879811/125299148-1bb2f300-e2e6-11eb-8095-7e063f6eae02.jpg)

**Comment by 4ian** [comment]
Great job! Fix applied, thanks! 👍

**Comment by dyvinevalentine** [comment]
nice this works great now
