### ISSUE TITLE
3D Flip

### ISSUE THREAD

**Issue by VegeTato** [GDevelopApp/GDevelop-extensions#184]
![3D flip extension](https://user-images.githubusercontent.com/81715237/125967031-9e9cb69e-f6e9-4e38-81fa-9ce387134aad.gif)

This extension is useful to give your game the 3D feeling, yet cute feeling to the players characters.
= = = = = = = = = = = = = = = = = = = = = =
**You can test the extension here:**
https://games.gdevelop-app.com/game-92062a3c-ea9d-4e14-9454-d375dca71ba1/index.html

Version 0.1
-------------------
-User can set the 3D flip speed
-User can set the object Width
-User can set the Right and Left keys
-User can change the ("Origin" point) to object center for the best results

Version 0.2
-------------------
-Added condition to check IF the object is 3D flipped (Helpful to make sound when object/player is 3D flip)

Version 0.3
-------------------
-User don't have to set the width anymore

## Checklist
- [done] Extension has a proper name and description.
- [done] Extension has tags (for example: "platform, brick, breakable").
- [done] All behaviors have a description.
- [done] All functions (actions, conditions, expressions) have descriptions and proper sentences.
- [done] I've followed the best practices listed on http://wiki.compilgames.net/doku.php/gdevelop5/extensions/best-practices
- [done] I confirm that this extension can be integrated to this GitHub repository, distributed and MIT licensed.

**You can download the example here:**
https://trello-attachments.s3.amazonaws.com/5fd532f01e99c97130e99fe9/60d0a6d728e99c7fc00c0d71/d8cccda5672fd75e3fdedf3058a3bfbd/3D_Flip_extension_Example_V0.2.rar

**You can download the extension here:**
https://trello-attachments.s3.amazonaws.com/5fd532f01e99c97130e99fe9/60d0a6d728e99c7fc00c0d71/000cd56bf954a99b488bf63b717d3467/3D_Flip_extension_v0.3.rar

**Comment by arthuro555** [comment]
[3D Flip extension Example.zip](https://github.com/GDevelopApp/GDevelop-extensions/files/6835364/3D.Flip.extension.Example.zip)
[ThreeDFlip.zip](https://github.com/GDevelopApp/GDevelop-extensions/files/6835365/ThreeDFlip.zip)

I have made some changes:
- Converted to a behavior
- Changed some properties to respect the best practices
- Added some actions/conditions

I have made major changes to the extension so I would appreciate another review, if none comes in a few days I'll add it.

**Comment by VegeTato** [comment]
> 
> 
> [3D Flip extension Example.zip](https://github.com/GDevelopApp/GDevelop-extensions/files/6835364/3D.Flip.extension.Example.zip)
> [ThreeDFlip.zip](https://github.com/GDevelopApp/GDevelop-extensions/files/6835365/ThreeDFlip.zip)
> 
> I have made some changes:
> 
>     * Converted to a behavior
> 
>     * Changed some properties to respect the best practices
> 
>     * Added some actions/conditions
> 
> 
> I have made major changes to the extension so I would appreciate another review, if none comes in a few days I'll add it.

-pressing both Left + Right keys at the same time will spin the character endless
-pressing left then right or right then left Fast, will cause the flip sound to not work

**Comment by arthuro555** [comment]
Those are not bugs with the extension just the example not using trigger onces and and not considering a flip can be canceled . Here is the updated example: 
[3D Flip extension Example.zip](https://github.com/GDevelopApp/GDevelop-extensions/files/6835944/3D.Flip.extension.Example.zip)

**Comment by Bouh** [comment]
Great extension, thanks for the reviews guys!

About action **Cancel the flip**, the description shows **Stops** and the title **Cancel** and the action pause the flipping animation.

Which one I should keep? Cancel or stop, actually it stop:
![1_flipstop](https://user-images.githubusercontent.com/1670670/126330334-a7f373cb-fd5b-4f44-99a1-a5b0aa6d0463.gif)

**Comment by 4ian** [comment]
Should be "stop" then :) ("cancel" would mean to go back to the previous state)

**Comment by Bouh** [comment]
Closed by 3fbd4dfe2e1a42674b26e47f1ca49757e5103a69
