### ISSUE TITLE
Fight system

### ISSUE THREAD

**Issue by VegeTato** [GDevelopApp/GDevelop-extensions#187]
![Finished](https://user-images.githubusercontent.com/81715237/125970553-654dbb23-3e18-45ce-9fef-fba1073fc87e.gif)

Useful for fight games system
Examples: (Street fighter / mortal kombat / street of rage...etc)
This extension can save users a lot of time when it comes to combats (Melee or Range)
it takes so much time to make events and variables and timers and animations and keys
and all of this JUST to make the player fight with 1 button but make Combos !
such as T > T > T
same thing to ability such as: S > D > S > D > G = Do ability !
and many other things users would need to make a fight system for their games.

**You can test the extension here:**
https://vegetato.itch.io/fight-system-extension-text?secret=43OFZGfCsizMNv071KWY68Zb0o

  Version 0.1
-----------------------------------
-User can pick up to 3 punches systems
-User can pick the idle animation number
-User can pick the punch animation number/name
-User can pick the punch key
-User can choose the time before the player goes back to idle
-User can choose the delay(speed) between the punches

  Version 0.2
-----------------------------------
-User can set Enemy damaged animation
-User can set the distance between the player and the enemy in order to make the enemy take damage
-User can set the enemy idle position (before/after he took damage)
-User can set the Time before the enemy goes back to his idle position

  Version 0.3
-----------------------------------
-Fixed bug when holding punch button enemy punched animation gets stuck
-User can check what will happen to the enemy in the game events (Actions)
-User can Add a condition to (Check if the player is fighting)
-User can SHAKE the enemy when he gets damaged (can be turned ON or OFF)

  Version 0.4
-----------------------------------
-Added new condition, User can check in what punch the player is currently at
(useful for last hit combo)
-Added users can name the timers for multi enemies
-Fixed bug on multi enemies shakes when one of them get punched
-Fixed bug on multi enemies moves when one of them get punched
-Fixed bug when player keep moving while fighting

  Version 0.5
-----------------------------------
-Added ability to do Jump attacks
-Added ability to Block attacks
-Extension work on Multi players with no conflicts
-Added new Condition/action to check if player is Blocking
-Added new condition/action to check if player is dead or to make him die (turn off the extension)
-Fixed many bugs

  Version 0.6
-----------------------------------
-added Combo keys Condition for abilities, Example: (s>d>s>d>t  > Ability)

  Version 0.7
-----------------------------------
-Fixed a major bug was making conflicts with attacks and new combo conditions
-Fixed Major bug was making attacks work while player is Blocking

Version 0.8
-----------------------------------
-Fixed major bug when player do ability While he is Dead, he get up
-Fixed major bug when player do jump attack button while he is Dead, he kick
-Variables now have unique names to not make conflicts with the user variables
-Removed trigger once from is dead function to leave the option for the user
-Fixed few English spelling mistakes in parameters 

## Checklist
- [done] Extension has a proper name and description.
- [done] Extension has tags (for example: "platform, brick, breakable").
- [done] All behaviors have a description.
- [done] All functions (actions, conditions, expressions) have descriptions and proper sentences.
- [done] I've followed the best practices listed on http://wiki.compilgames.net/doku.php/gdevelop5/extensions/best-practices
- [done] I confirm that this extension can be integrated to this GitHub repository, distributed and MIT licensed.

**You can download the example here:**
https://trello-attachments.s3.amazonaws.com/5fd532f01e99c97130e99fe9/6088a83dd488c34fd0f2f776/824f495f8c20ce8587619d22b44440cb/Fight_system_extension_example.zip

**You can download the extension here:**
https://trello-attachments.s3.amazonaws.com/5fd532f01e99c97130e99fe9/6088a83dd488c34fd0f2f776/6ffdd9c04b341c865e23cf57af81be0c/Fight_system_extension_V0.8.zip

**Comment by DHsoftw** [comment]
Things that I think the extension needs:

**Comment by arthuro555** [comment]
Could you try converting the extension to a behavior please?

**Comment by Bouh** [comment]
We are closing this thread.
You can continue to discuss here and we will reopen the thread when an update to the extension is available.
