### ISSUE TITLE
Average Values of Multiple Objects (Was: "FindCenterOfObjects: Find the center of a group of objects")

### ISSUE THREAD

**Issue by tristanbob** [GDevelopApp/GDevelop-extensions#189]
## Describe the extension

Provide X and Y position values for the center of a group of objects.

## Checklist
- [x] Extension has a proper name and description.
- [x] Extension has tags (for example: "platform, brick, breakable").
- [x] All behaviors have a description.
- [x] All functions (actions, conditions, expressions) have descriptions and proper sentences.
- [x] I've followed the best practices listed on http://wiki.compilgames.net/doku.php/gdevelop5/extensions/best-practices
- [x] I confirm that this extension can be intergrated to this GitHub repository, distributed and MIT licensed.

## Play here

https://games.gdevelop-app.com/game-23fde65c-7992-4ba6-9219-d90b670867bf/index.html

## Extension file

[FindCenterOfObjectsExtension_0.1.5.json.zip](https://github.com/GDevelopApp/GDevelop-extensions/files/6835196/FindCenterOfObjectsExtension_0.1.5.json.zip)

## Project files

[FindCenterOfObjects.zip](https://github.com/GDevelopApp/GDevelop-extensions/files/6835199/FindCenterOfObjects.zip)

## Video

https://user-images.githubusercontent.com/8879811/126047490-c6a19718-574f-4c17-8a6d-bd5b0aac7129.mp4

**Comment by Midhil457** [comment]
Hi, I really liked the extension. After playing with it for some time, I have some suggestions

- Providing conditions might be helpful, but users can always use compare numbers though 
- Is it possible to make it calculate with different objects and not only just the same object?
- The description is a bit short on info

:)

**Comment by tristanbob** [comment]
> * Providing conditions might be helpful

I'm not sure conditions make sense for an expression, but I might be wrong.  What would the conditions be?  Do other "expression-only" extensions provide conditions?  

> * Is it possible to make it calculate with different objects and not only just the same object?

Yes, you would just use an object group instead of a single object.

> * The description is a bit short on info

This is a very simple expression (but one that is useful for a lot of reasons.)  What do you think would be useful for users?  I guess I could explain some use-cases (like flocking behaviors, camera tracking, etc)

**Comment by 4ian** [comment]
As it's a very simple extension I think it's better to keep just the expression.
In the future, we'll add a capability so that extensions can declare an expression and automatically get a condition made from it :)

**Comment by Midhil457** [comment]
Makes sense
> This is a very simple expression (but one that is useful for a lot of reasons.) What do you think would be useful for users? I guess I could explain some use-cases (like flocking behaviors, camera tracking, etc)

Yes, I didn't realize that it can be used for camera tracking until now, so the use case would be useful

- One suggestion, the icon is doesn't look very related to the extension. I wasn't able to find many that made sense, so I am not sure
![center](https://user-images.githubusercontent.com/73597906/126338125-ab63d3c8-65e7-4f06-8da6-0283cf18ab1c.PNG)Maybe this will work?

:)

**Comment by 4ian** [comment]
This icon looks a bit more suitable yes 👍

**Comment by tristanbob** [comment]
Please hold on adding this; I'd like to add some more "related" expressions. 

- GroupMinX
- GroupMaxX
- GroupMinY
- GroupMaxY

Do you have any ideas on other expressions to include?

**Comment by Midhil457** [comment]
TopX,TopY, BottomX and Bottom Y?

**Comment by tristanbob** [comment]
> TopX,TopY, BottomX and Bottom Y?

What is the goal with this?  To return the x,y of the top object (and the bottom object)?

I think I am going to add more functions that will help with RTS flocking and unit movement.

- GroupAverageHeading (or should I call it "GroupAverageAngle"?)
- GroupAverageVelocityY
- GroupAverageVeloctyX

Reference:

https://gamedevelopment.tutsplus.com/tutorials/3-simple-rules-of-flocking-behaviors-alignment-cohesion-and-separation--gamedev-3444

**Comment by tristanbob** [comment]
Adding more to todo list:

- NeighborCount 
"PrimaryObject"
NeighborObject"

**Comment by Bouh** [comment]
Is there a specific bottleneck or expectation that would help in the implementation of this extension?
Part of this was added in your RTS game?

**Comment by tristanbob** [comment]
Eeek, please don't abandon this quite yet.  :)   I will have a lot more time to work on game dev in about 3 weeks.  I'm currently much more busy than normal due to an event-based commitment. 

When I get time, I will focus on finishing this extension (and perhaps others) before doing fun new stuff.   Thanks Bouh!

**Comment by tristanbob** [comment]
I think I'm done for now.  :)  Let's get the review process started.  Thanks for bearing with me!

## Version 1.0.0

Provides average values of a group of objects.  Useful for camera tracking, AI flocking behaviors, and more.

Included expressions:

Center position (mean)
- X center position of a group of objects 
- Y center position of a group of objects

Center position (medium)
- X center position of a group of objects 
- Y center position of a group of objects 

Based on center of object:
- Minimum X position of a group of objects
- Maximum X position of a group of objects
- Minimum Y position of a group of objects
- Maximum Y position of a group of objects

Based on AABB of object:
- Minimum X position of a group of objects
- Maximum X position of a group of objects
- Minimum Y position of a group of objects
- Maximum Y position of a group of objects

- Average horizontal force (X) of a group of objects
- Average vertical force (Y) of a group of objects

## Extension file
[AverageValuesOfObjects_Extension_1.0.0.json.zip](https://github.com/GDevelopApp/GDevelop-extensions/files/7319560/AverageValuesOfObjects_Extension_1.0.0.json.zip)

## Playable game
https://games.gdevelop-app.com/game-c418ef6d-93bc-4564-92b0-826625751ec1/index.html

## Project files
[AverageValuesOfObjects.zip](https://github.com/GDevelopApp/GDevelop-extensions/files/7319538/AverageValuesOfObjects.zip)

## Video
https://twitter.com/VictrisGames/status/1447418614600982530
