### ISSUE TITLE
Regular Expressions Extension

### ISSUE THREAD

**Issue by Add00** [GDevelopApp/GDevelop-extensions#190]
## Describe the extension
This extension implements JavaScript regular expressions into GDevelop.

## Checklist
- [x] Extension has a proper name and description.
- [x] Extension has tags (for example: "platform, brick, breakable").
- [x] All behaviors have a description.
- [x] All functions (actions, conditions, expressions) have descriptions and proper sentences.
- [x] I've followed the best practices listed on http://wiki.compilgames.net/doku.php/gdevelop5/extensions/best-practices
- [x] I confirm that this extension can be intergrated to this GitHub repository, distributed and MIT licensed.

## Example
[game.zip](https://github.com/GDevelopApp/GDevelop-extensions/files/6842659/game.zip)

## Extension file
[RegExp.zip](https://github.com/GDevelopApp/GDevelop-extensions/files/6841432/RegExp.zip)

**Comment by arthuro555** [comment]
Lgtm, I have made a few changes to the names and description and turned some expressions into actions/conditions:
[game.zip](https://github.com/GDevelopApp/GDevelop-extensions/files/6889059/game.zip)
