### ISSUE TITLE
Draw pathfinding

### ISSUE THREAD

**Issue by Entr0py404** [GDevelopApp/GDevelop-extensions#192]
## Describe the extension
Draw the pathfinding of an object using a shape painter.
![ypETnaqHdp](https://user-images.githubusercontent.com/75917656/127233732-87b59b9a-bc9a-48d2-848d-e998211cb20f.gif)

## Checklist
- [x] Extension has a proper name and description.
- [x] Extension has tags (for example: "platform, brick, breakable").
- [x] All behaviors have a description.
- [x] All functions (actions, conditions, expressions) have descriptions and proper sentences.
- [x] I've followed the best practices listed on http://wiki.compilgames.net/doku.php/gdevelop5/extensions/best-practices
- [x] I confirm that this extension can be intergrated to this GitHub repository, distributed and MIT licensed.

## Example
[Draw Pathfinding Extension Example.zip](https://github.com/GDevelopApp/GDevelop-extensions/files/6888981/Draw.Pathfinding.Extension.Example.zip)

## Extension file
[DrawPathfinding.zip](https://github.com/GDevelopApp/GDevelop-extensions/files/6888980/DrawPathfinding.zip)

**Comment by arthuro555** [comment]
LGTM!

**Comment by 4ian** [comment]
Nice 👍
