### ISSUE TITLE
Coyote Time

### ISSUE THREAD

**Issue by Entr0py404** [GDevelopApp/GDevelop-extensions#193]
## Describe the extension
Adds the ability for the player to jump even after their character is no longer touching the ground, for a given amount of time.
![PtUCC8aO7d](https://user-images.githubusercontent.com/75917656/127248835-05af6957-739d-420d-b252-2b6c7bcc24af.gif)

## Checklist
- [x] Extension has a proper name and description.
- [x] Extension has tags (for example: "platform, brick, breakable").
- [x] All behaviors have a description.
- [x] All functions (actions, conditions, expressions) have descriptions and proper sentences.
- [x] I've followed the best practices listed on http://wiki.compilgames.net/doku.php/gdevelop5/extensions/best-practices
- [x] I confirm that this extension can be intergrated to this GitHub repository, distributed and MIT licensed.

## Example
[Coyote Time Extension Example.zip](https://github.com/GDevelopApp/GDevelop-extensions/files/6889665/Coyote.Time.Extension.Example.zip)

## Extension file
[CoyoteTime.zip](https://github.com/GDevelopApp/GDevelop-extensions/files/6889660/CoyoteTime.zip)

**Comment by 4ian** [comment]
That's a good addition to have :) 
But currently seems that there is a bug, as I can jump for easily one second after starting to fall.

I think the logic should be reversed: we should allow to jump when the character is not on the floor anymore, and then disallow to jump again after a bit of time... but I think there is no easy way to do this 😬
We should add a "Disallow to jump again" to the platformer behavior!

Also note that this kind of extension could be easier to do in the feature thanks to behavior composition that @D8H started to implement. This means that you'll be able to have another behavior as a required behavior :)

**Comment by D8H** [comment]
This will be a really good extension.

Some games also help the reception on a platform to avoid falling for few pixels. But this might be hard to implement outside of the platformer behavior.

https://github.com/4ian/GDevelop/pull/2872

**Comment by D8H** [comment]
Hello Entropy, since the beta 117, it's possible to make this extension. You can require a Platformer Character using a behavior property.

**Comment by Entr0py404** [comment]
I don't understand the inverse method so can't

**Comment by D8H** [comment]
> I don't understand the inverse method so can't

It was difficult to find a short description that explained it clearly.
* When the character is on the floor, this action as no impact, the player can still jump.
* When the character is jumping or falling, this action forbids the character to jump again until it reach the floor.

In the case of this extension, it could allow to disable the jump when the player is falling for N milliseconds.
