### ISSUE TITLE
Magnetic Effect

### ISSUE THREAD

**Issue by Entr0py404** [GDevelopApp/GDevelop-extensions#195]
## Describe the extension
With this behavior, you can attract an object to another object, such as coins attracted to a player.
![FgszB1u0PT](https://user-images.githubusercontent.com/75917656/127251841-14c7ca8b-4376-42b7-93d8-e72dec52c0d1.gif)

## Checklist
- [x] Extension has a proper name and description.
- [x] Extension has tags (for example: "platform, brick, breakable").
- [x] All behaviors have a description.
- [x] All functions (actions, conditions, expressions) have descriptions and proper sentences.
- [x] I've followed the best practices listed on http://wiki.compilgames.net/doku.php/gdevelop5/extensions/best-practices
- [x] I confirm that this extension can be intergrated to this GitHub repository, distributed and MIT licensed.

## Example
[Magnetic Effect Extension Example.zip](https://github.com/GDevelopApp/GDevelop-extensions/files/6889781/Magnetic.Effect.Extension.Example.zip)

## Extension file
[MagneticEffect.zip](https://github.com/GDevelopApp/GDevelop-extensions/files/6889779/MagneticEffect.zip)

**Comment by 4ian** [comment]
Looks nice!
A few nitpicking:
- Rate should be named Speed. Also include the unit in the sentence ("a rate of _PARAM4_ " => "a speed of _PARAM4_px/s")
- Distance should be "Minimum distance". In the sentence, also change "within a distance below _PARAM3_" to "(until the minimum distance of _PARAM3_px)"
- In the sentence, add punctuation for "permanently _PARAM5_" =>  "(permanently: _PARAM5_)"

I'll probably also adapt the descriptions of the behaviors/extensions, you can let this to me :)

**Comment by ClementPasteau** [comment]
Thanks for this extension!

I've also noticed that the logic of the behavior has some actions duplicated between "Permanent" and "non-permanent" that could be moved outside of any condition on the permanent boolean :)

I'll take it from here to publish it!

**Comment by arthuro555** [comment]
@ClementPasteau Remember to close the issue after adding the extension ;)
