### ISSUE TITLE
EasyButton - Create a button with text and idle/hover state

### ISSUE THREAD

**Issue by UlisesFreitas** [GDevelopApp/GDevelop-extensions#197]
## EasyButton

Create a button with two animations idle and hover, the button can be identified with a string so later it's easy to manage the states of the button. 

After you create one button you can add two kinds of conditions Hover or Clicked
Hover means the mouse is over the button so the animation changes and this condition returns true.
Clicked means the button was clicked and the condition returns true

## Checklist

- [x] Extension has a proper name and description.
- [x] Extension has tags (for example: "platform, brick, breakable").
- [x] All behaviors have a description.
- [x] All functions (actions, conditions, expressions) have descriptions.
- [x] I confirm that this extension can be intergrated to this GitHub repository, distributed and MIT licensed.

## Extension file
https://github.com/UlisesFreitas/EasyButton-GDevelop-Extension-/blob/main/EasyButton.zip

## Extension example
https://github.com/UlisesFreitas/EasyButton-GDevelop-Extension-
https://www.youtube.com/watch?v=46Qp1WXbZMI

## Live example
https://games.gdevelop-app.com/game-a9cb40cd-5b71-492c-9ce2-6e8e64921659/index.html

## Extension .json file.
https://github.com/UlisesFreitas/EasyButton-GDevelop-Extension-/blob/main/EasyButton.json

For the reviewer there is some issue given the quantity of parameters some times the title of the extension is not visible but the extension works fine. Maybe you need to fix the size of the frameholder.
Look:
https://ibb.co/nMxD70v
As you can see the scrollbar is at the top but you can't see the Extension title and link

**Comment by UlisesFreitas** [comment]
Hi I updated this to 1.0.1 added a new function/Condition to update the button if the size is changed then the button is updated
https://github.com/UlisesFreitas/EasyButton-GDevelop-Extension-/releases/tag/1.0.1
The project is updated too.

**Comment by arthuro555** [comment]
Hello 👋 

I've looked quickly at the extension, and I think it would better fit as a custom behavior. You can also check out #17, it seemed more advanced but has been abandoned by the original author. If you want you can take over the task of finishing it.
