### ISSUE TITLE
EasyFullscreen

### ISSUE THREAD

**Issue by UlisesFreitas** [GDevelopApp/GDevelop-extensions#198]
#EasyFullscreen
A simple extension to allow you to toggle between windowed and fullscreen in your game.

#Parameters 1: 
Keyboard Text: allow to pick which key you want to use to toggle fullscreen.

# Scene variable: __EasyFullscreen_fullscreen - type(bool)
Use a bool scene variable to check if the the game is windowed or fullscreen
* If true: go fullscreen.
* If false: go windowed.

Preview: https://www.youtube.com/watch?v=_3OYLCOOQs8
Example: https://github.com/UlisesFreitas/EasyFullscreen-GDevelop-Extension-

## Checklist

- [x] Extension has a proper name and description.
- [x] Extension has tags (for example: "platform, brick, breakable").
- [x] All behaviors have a description.
- [x] All functions (actions, conditions, expressions) have descriptions.
- [x] I confirm that this extension can be intergrated to this GitHub repository, distributed and MIT licensed.

## Extension file
As JSON: https://github.com/UlisesFreitas/EasyFullscreen-GDevelop-Extension-/blob/main/EasyFullscreen.json

As .zip: https://github.com/UlisesFreitas/EasyFullscreen-GDevelop-Extension-/blob/main/EasyFullscreen.zip

Sample project: 
https://github.com/UlisesFreitas/EasyFullscreen-GDevelop-Extension-/blob/main/gd-project-EasyFullscreen.zip

Preview: 
https://www.youtube.com/watch?v=_3OYLCOOQs8

Finally, attach the .json file of your extension here.

As JSON: https://github.com/UlisesFreitas/EasyFullscreen-GDevelop-Extension-/blob/main/EasyFullscreen.json
As .zip: https://github.com/UlisesFreitas/EasyFullscreen-GDevelop-Extension-/blob/main/EasyFullscreen.zip

You also may have to create an account on GitHub before posting.
If your extension is high quality and useful, it will be added to the list of GDevelop community extensions.
When you're ready, remove this last paragraph and click on "Submit new issue". Thanks 🙌

**Comment by Bouh** [comment]
I don't think we should accept this extension, it's reduced to a toggle of two actions and completely hides the conditions that affect them.
The gain is not obvious, it's rather recommended to educate users to do this kind of simple thing.
[A page in the documentation explains this.](http://wiki.compilgames.net/doku.php/gdevelop5/tutorials/how-to-make-togglable-states-with-variables#toggling_the_state)
