### ISSUE TITLE
UUID extension

### ISSUE THREAD

**Issue by arthuro555** [GDevelopApp/GDevelop-extensions#201]
## Describe the extension
Adds expressions to generate unique IDs

## Checklist
- [X] Extension has a proper name and description.
- [X] Extension has tags (for example: "platform, brick, breakable").
- [X] All behaviors have a description.
- [X] All functions (actions, conditions, expressions) have descriptions and proper sentences.
- [X] I've followed the best practices listed on http://wiki.compilgames.net/doku.php/gdevelop5/extensions/best-practices
- [X] I confirm that this extension can be intergrated to this GitHub repository, distributed and MIT licensed.

## Example
It's my extensions experiments file, don't mind all the other stuff. To test that one type either `uuid_v4` or `uuid_ii` in the preview window then the `Return` key.  
[ExtensionsWorkbench.zip](https://github.com/GDevelopApp/GDevelop-extensions/files/7008515/ExtensionsWorkbench.zip)

## Extension file
[UUID.zip](https://github.com/GDevelopApp/GDevelop-extensions/files/7008511/UUID.zip)

**Comment by UlisesFreitas** [comment]
It's interesting how to use this UUID extension? there is an example?

**Comment by 4ian** [comment]
This extension is giving two expressions that you can use in games :)
@arthuro555: there are typos/bad punctuation in the description, double check that ;) Try something like grammarly.com to find these easily. Otherwise looks ok, though I wonder if we really need to expose the increasing counter "UID" - it sounds complicated for a variable doing +1 at each call. Might be better to leave the users do that by themselves?

**Comment by arthuro555** [comment]
Ah, sorry for that, I'll check. 
>  though I wonder if we really need to expose the increasing counter "UID" - it sounds complicated for a variable doing +1 at each call. Might be better to leave the users do that by themselves?

Personally, I find it easier to have just one expression for doing that and is something used by GDevelop users currently quite often when generating IDs (though it makes the extension name a misnomer as it is a Unique ID not a Universally Unique ID).

**Comment by arthuro555** [comment]
[UUID.zip](https://github.com/GDevelopApp/GDevelop-extensions/files/7023925/UUID.zip)
Ok, what about now? I think I checked everything.

**Comment by Bouh** [comment]
Needs a skilled humain for spot typos, however lgtm.

**Comment by arthuro555** [comment]
Grammarly says everything is ok, so if everything is fine I'll go ahead and merge.
