### ISSUE TITLE
Position Checkpoints for Instances

### ISSUE THREAD

**Issue by ElairyxOfficial** [GDevelopApp/GDevelop-extensions#202]
## Describe the extension
This extension allows to set up checkpoints for instances. Checkpoint coordinates are dynamic values so can be object positions, absolute/relative values and more. Checkpoints can then be used to move the same or even other instances to them.

Not existing checkpoints (not defined, with default value 0) can be ignored. This can be decided per instance/per action.

## Extension contains
**ACTION:** Save checkpoint (saves a position as a checkpoint)
**ACTION:** Load checkpoint (move object to checkpoint position)
**CONDITION:** Checkpoint exists (checks if checkpoint has been saved yet)

## Checklist
- [x] Extension has a proper name and description.
- [x] Extension has tags (for example: "platform, brick, breakable").
- [x] All behaviors have a description.
- [x] All functions (actions, conditions, expressions) have descriptions and proper sentences.
- [x] I've followed the best practices listed on http://wiki.compilgames.net/doku.php/gdevelop5/extensions/best-practices
- [x] I confirm that this extension can be intergrated to this GitHub repository, distributed and MIT licensed.

## Example video and events

Check notes and explanations in the white/light blue comment

https://user-images.githubusercontent.com/83909121/132050328-371f381d-dd4e-4902-9648-7098df39040b.mp4

![checkpointMainEvents](https://user-images.githubusercontent.com/83909121/132050434-235684e1-e74f-4460-8b5c-b191a028b256.png)

## Example
Here is an example project for the extension.
[checkpoints-extention-improved.zip](https://github.com/GDevelopApp/GDevelop-extensions/files/7107849/checkpoints-extention-improved.zip)

## .json Extension file
Finally, attach the .json file of your extension here. (The single .json file as .zip)
[Extension.zip](https://github.com/GDevelopApp/GDevelop-extensions/files/7107852/Extension.zip)

**Comment by tristanbob** [comment]
Uh oh looks like the bot made a mistake!  This should not be closed.

**Comment by ElairyxOfficial** [comment]
> Uh oh looks like the bot made a mistake! This should not be closed.

"The way the bot was set up is pretty dumb, it closes any issue that has "Attach a sample project with resources to test the extension." in it" - according to arthuro. I've now removed it not that is causes more issues...

**Comment by Bouh** [comment]
Hi @ElairyxOfficial 

- What do you think to allow the user to choose the name of the checkpoint instead of hardcoded Primary and Secondary?
[This can be achieved by structured variables.](http://wiki.compilgames.net/doku.php/gdevelop5/all-features/firebase/realtime_database#comparison_with_structure_variables)
- If Arrays are used you will be able to propose an action to pick for example the 5th checkpoint in this array.
- Variables must start in you extension by `__Checkpoints_.`  like `__Checkpoints_.Primary.X`, if you prefer a structure variable:  `__Checkpoints_.Checkpoint[CHECKPOINTNAME].X`
- Parameter name must be simple as `SaveObject` no underscore or special characters.
- [The best practice guide](http://wiki.compilgames.net/doku.php/gdevelop5/extensions/best-practices)

**Comment by ElairyxOfficial** [comment]
Thank you, @Bouh for your reply.
I originally planned to not only have only the two checkpoints but by the time I didn't really get the arrays to work and accidentally only asked for help when the extension was already submitted...

I will try to get arrays/structured variables implemented asap - which I'm afraid I can't get to until the weekend or so.

Also, I'm sorry if I have missed putting the variable names in the correct format, I occasionally work with "regular" names and replace them afterwards but I guess that didn't make it this time :o

**Comment by ElairyxOfficial** [comment]
Hello @Bouh,
I have made the changes and updated the issue with the correct files, a new video and image. I have worked through the Best Practices guide and have added the extension prefix to the object variables.
I hope that everything is fine now :)

**Comment by ElairyxOfficial** [comment]
I will have to look over the game and extension files myself again. With the next here by me published version of the extension, I'm done checking through everything myself again. Until then, feel free to move this to "Needs change" if wanted/needed.

**Comment by Bouh** [comment]
I've made the latest changes on variables, functions, game properties, naming, etc...
Thank you for this new extension 🎉
