### ISSUE TITLE
Return FPS expression

### ISSUE THREAD

**Issue by Ahnaf30e** [GDevelopApp/GDevelop-extensions#203]
## Describe the extension
It can be used to get the fps of the game and it also gives its answer fast.

## Checklist
- [x] Extension has a proper name and description.
- [x] Extension has tags (for example: "platform, brick, breakable").
- [x] All functions (actions, conditions, expressions) have descriptions and proper sentences.
- [x] I've followed the best practices listed on http://wiki.compilgames.net/doku.php/gdevelop5/extensions/best-practices
- [x] I confirm that this extension can be intergrated to this GitHub repository, distributed and MIT licensed.

## Example
[labtestroom - Copy.zip](https://github.com/GDevelopApp/GDevelop-extensions/files/7027017/labtestroom.-.Copy.zip)

## Extension file
[fps1.zip](https://github.com/GDevelopApp/GDevelop-extensions/files/7027021/fps1.zip)

**Comment by arthuro555** [comment]
Huh, I am kind of surprised this did not already exist. I made a few changes in the sentences, added a few tags, an expression that allows getting the FPS without specifying any padding and a behavior for showing the FPS.
If you are OK with those changes, I'll merge it. If you disagree with any of those changes, please let us know, and I'll revert them before merging.
[labtestroom - Copy.zip](https://github.com/GDevelopApp/GDevelop-extensions/files/7027387/labtestroom.-.Copy.zip)

**Comment by 4ian** [comment]
LGTM! 👍
nitpicking: "Adds tools" => Prefer to tell what it is adding directly (expressions and a behavior for text objects).

**Comment by Bouh** [comment]
I'll review, fix and merge this in the next 24h :)

**Comment by arthuro555** [comment]
> I'll review, fix and merge this in the next 24h :)

Ah, sorry, I got the email notification for that message a few seconds after pushing 😓

**Comment by Bouh** [comment]
haha you know I was like, *but I can do it now*, and I come back on my bookmark, it's already done :') 
Nevermind thanks you so much!
