### ISSUE TITLE
Choose Random Number or String given a string of values

### ISSUE THREAD

**Issue by UlisesFreitas** [GDevelopApp/GDevelop-extensions#209]
# Choose

## How to use it
Choose from list of given string of values and return one of the randomly

## How to use it
Create a new variable of the type you want Number/String then go to Functions and select Choose::RandomString or Choose::RandomNumber and set the values you want to randomize separated by commas.
Done.

## Extra
Check a mini tutorial: https://youtu.be/h0uLECuAwko
Here the project: https://drive.google.com/file/d/1ydRdbEsFX-MVKaWv6lpq7GAeWEkBQiCr

## Checklist

- [x] Extension has a proper name and description.
- [x] Extension has tags (for example: "platform, brick, breakable").
- [x] All behaviors have a description.
- [x] All functions (actions, conditions, expressions) have descriptions.
- [x] I confirm that this extension can be intergrated to this GitHub repository, distributed and MIT licensed.

## Extension file
[Choose.zip](https://github.com/GDevelopApp/GDevelop-extensions/files/7064856/Choose.zip)

**Comment by 4ian** [comment]
Nice! A good idea to have an extension like this.

I've simplified the whole implementation from this:
![image](https://user-images.githubusercontent.com/1280130/132090625-d992f6bd-f1c7-4bb2-801b-bac6ebbaddb0.png)

to this:
![image](https://user-images.githubusercontent.com/1280130/132105437-dbe610a1-afb2-444b-b604-f92d62c7d477.png)

There was actually no need to use GDevelop variables here, JS variables are fine :) 
I've also updated various descriptions.

Thanks for submitting this, this will be very useful I think to have this capability.

**Comment by arthuro555** [comment]
Actually, I was reviewing this too and had already rewritten it with GDevelop events 👀

**Comment by 4ian** [comment]
Ah sorry for the useless work then.. I should have said I was on it!

**Comment by UlisesFreitas** [comment]
Thank you all for taking into account.

**Comment by arthuro555** [comment]
Well, in case anyone is interested here is my events based version (number version not working for an unknown reason): 
[game.zip](https://github.com/GDevelopApp/GDevelop-extensions/files/7110401/game.zip)
