### ISSUE TITLE
Extra Animation Tools

### ISSUE THREAD

**Issue by Ahnaf30e** [GDevelopApp/GDevelop-extensions#214]
## Describe the extension
Use this extension for various animation related things that can't be accessed or edited from events

## Checklist
- [x] Extension has a proper name and description.
- [x] Extension has tags (for example: "platform, brick, breakable").
- [x] All behaviors have a description.
- [x] All functions (actions, conditions, expressions) have descriptions and proper sentences.
- [x] I've followed (most of) the best practices listed on http://wiki.compilgames.net/doku.php/gdevelop5/extensions/best-practices
- [x] I confirm that this extension can be integrated to this GitHub repository, distributed and MIT licensed.

## Example
[realExtraAnim.zip](https://github.com/GDevelopApp/GDevelop-extensions/files/7141748/realExtraAnim.zip)

## Extension file
[stuffAnimExtra.zip](https://github.com/GDevelopApp/GDevelop-extensions/files/7141779/stuffAnimExtra.zip)

**Comment by arthuro555** [comment]
[![Best practices say no](https://user-images.githubusercontent.com/19349038/132821116-33d32fa2-9b3d-44ac-8b81-f435ef7d9769.png)](https://wiki.compilgames.net/doku.php/gdevelop5/extensions/best-practices#no_usage_of_private_methods_or_variables_starting_with)

**Comment by Ahnaf30e** [comment]
oh ok, you can close this if you want to

**Comment by Ahnaf30e** [comment]
btw, is there any alternative way of doing this?
