### ISSUE TITLE
Rectangular Movement (version 0.2.0)

### ISSUE THREAD

**Issue by tristanbob** [GDevelopApp/GDevelop-extensions#216]
## Version 0.2.0

- Added conditions to check which direction the object is moving (allows users to change animations, rotate object, etc)
  - IsMovingUp, IsMovingDown, IsMovingLeft, IsMovingRight
  - https://forum.gdevelop-app.com/t/solved-rectangle-function/35003/3
- Updated movement so that "constant speed" and "variable speed" options will travel the same distance. 
  - Allows gamedevs to easily try the different modes without recalculating the right movement values
-  Cleaned up some events to reduce repeated code (DRY principle) 

## Example

https://games.gdevelop-app.com/game-2a59f5cf-65c1-4d87-b2fa-b31d094d06d1/index.html

## Extension file

[RectangularMovementExtension_0.2.0.json.zip](https://github.com/GDevelopApp/GDevelop-extensions/files/7148454/RectangularMovementExtension_0.2.0.json.zip)

## Project folder

[RectangularMovement_SourceFiles.zip](https://github.com/GDevelopApp/GDevelop-extensions/files/7148450/RectangularMovement_SourceFiles.zip)

## Video

https://user-images.githubusercontent.com/8879811/132960420-9a049059-a79a-448e-8940-50ed3cc1ebee.mp4

**Comment by 4ian** [comment]
Nice! Sorry for the lead time on this, @AlexandreSi will take a look at this! :D

**Comment by AlexandreSi** [comment]
Hi @tristanbob, thank you for the evolution, seems good to me!
Would you be ok to add your example to Gdevelop examples?
If so, I can take it from here!

**Comment by tristanbob** [comment]
Yes, of course!  I haven't cleaned up the project for submission, but you can certainly do it. :)
