### ISSUE TITLE
Spaceship behavior

### ISSUE THREAD

**Issue by Entr0py404** [GDevelopApp/GDevelop-extensions#222]
A simple spaceship behavior
Spaceship makes your object behave like a vehicle in outer space.
![lZ7Qp2EFTL](https://user-images.githubusercontent.com/75917656/134186739-6b92fafe-f13e-4642-94af-b0bfe874cbe3.gif)

## Checklist

- [x] Extension has a proper name and description.
- [x] Extension has tags (for example: "platform, brick, breakable").
- [x] All behaviors have a description.
- [x] All functions (actions, conditions, expressions) have descriptions.
- [x] I confirm that this extension can be intergrated to this GitHub repository, distributed and MIT licensed.

## Extension file
[Spaceship-1.0.3.zip](https://github.com/GDevelopApp/GDevelop-extensions/files/7219437/Spaceship-1.0.3.zip)

## Extension example
[Spaceship Extension Example.zip](https://github.com/GDevelopApp/GDevelop-extensions/files/7219439/Spaceship.Extension.Example.zip)

Notes: I putt acceleration / deceleration to  say "(in pixels per millisecond)" not sure if that is correct.
Ignoring default controls just ignores the acceleration control and doesn't affect the rotation following the mouse, this doesn't seem correct but I wasn't sure what to do.

**Comment by Entr0py404** [comment]
Updated the extension with VegeTato's suggestions.

**Comment by Entr0py404** [comment]
Updated the extension to simplify some events

**Comment by D8H** [comment]
This event can do a very similar result.
![SpaceshipWithTopDown](https://user-images.githubusercontent.com/2611977/134550146-24fc944d-d18b-4e41-bb24-85a754105cc9.png)
Maybe this extension could require a Top-Down behavior and focus on handling the mouse distance and other features?

The example with Top-down (game2.json)
https://www.dropbox.com/s/3juifmdtke4w7rs/Spaceship%20Extension%20Example%20TopDown.zip?dl=1

**Comment by Entr0py404** [comment]
Oh I didn't realize that you could do that with the top-down behavior I don't think this needs to be an extension then because it's only one line or so

**Comment by Entr0py404** [comment]
I noticed when I closed this issue the automation moved it to added to gdevelop
