### ISSUE TITLE
New extension: Return Game Version

### ISSUE THREAD

**Issue by UlisesFreitas** [GDevelopApp/GDevelop-extensions#232]
### Description

I made this simple extension since some users ask this in the forum
https://forum.gdevelop-app.com/t/game-version-to-variable/26120
https://forum.gdevelop-app.com/t/is-there-a-way-to-check-the-game-version-in-a-variable/32317

A simple extension string expression that returns the current version number the user set in Game settings->Properties

### How to use the extension

1. Simply add a Text Object 
2. Go to actions add Modify text 
3. Click Formula or write CurrentGameVersion::ReturnCurrentGameVersion() as value
4. Done

### Checklist

- [X] I've followed all of [the best practices](http://wiki.compilgames.net/doku.php/gdevelop5/extensions/best-practices).
- [X] I confirm that this extension can be integrated to this GitHub repository, distributed and MIT licensed.

### Example

[gd-project-CurrentGameVersion-1.0.0.zip](https://github.com/GDevelopApp/GDevelop-extensions/files/7230213/gd-project-CurrentGameVersion-1.0.0.zip)

### Extension file

[ReturnGameVersion.zip](https://github.com/GDevelopApp/GDevelop-extensions/files/7230214/ReturnGameVersion.zip)

**Comment by Bouh** [comment]
Thank you, added in https://github.com/GDevelopApp/GDevelop-extensions/commit/d4cf5a759942051a52e550250af0959582cc04cb !

I've made a change to the JS Events, we prefer using the [GDJS API](https://docs.gdevelop-app.com/GDJS%20Runtime%20Documentation/index.html).

Before:
`eventsFunctionContext.returnValue= gdjs.projectData.properties.version;`
After:
`eventsFunctionContext.returnValue = runtimeScene.getGame().getGameData().properties.version;`

Nit: **Format** is an option in the context menu in a JS event, we use it for cleaning and format the source code .

Tests: Ok
Registry file: Updated

**Comment by Bouh** [comment]
Thank again, done in https://github.com/GDevelopApp/GDevelop-extensions/commit/501e20107af33e248963e867fe9f1cb71b5909a8
