### ISSUE TITLE
Button

### ISSUE THREAD

**Issue by Alios5** [GDevelopApp/GDevelop-extensions#233]
### Description

Adds button animation effect bounce, zoom in, zoom out, etc...(Requires Tween behavior)
Detection of interaction with the button:
-is pressed
-is just pressed 
-is on(switch button)
-is release
The inspiration comes from godot.
coming soon the addition of text in the buttons.

### How to use the extension

This extension will make it easier to create and interact with the button

### Checklist

- [X] I've followed all of [the best practices](http://wiki.compilgames.net/doku.php/gdevelop5/extensions/best-practices).
- [X] I confirm that this extension can be integrated to this GitHub repository, distributed and MIT licensed.

### Example

[Extensions.zip](https://github.com/GDevelopApp/GDevelop-extensions/files/7230474/Extensions.zip)

### Extension file

[ButtonExtension.json.zip](https://github.com/GDevelopApp/GDevelop-extensions/files/7230478/ButtonExtension.json.zip)

**Comment by D8H** [comment]
Thank you for taking the time to submit an extension.
The game folder contains more than 1000 unused assets. It took 3 minutes to my computer to unzip it. Please, remove unused assets.
I'm not sure that the example is showing what you want
* The 4 buttons has the same settings (as they are the same object). You could make one object for each to set different settings and use a group if you need it. Maybe add a label to explain the setting of each button.
* In the events the 4 cases set the same text.
