### ISSUE TITLE
Update YandexGamesSDK

### ISSUE THREAD

**Issue by fedoric** [GDevelopApp/GDevelop-extensions#269]
### Description

Fixed the Show the rewarded video bug

### Checklist

- [X] I've followed all of [the best practices](http://wiki.compilgames.net/doku.php/gdevelop5/extensions/best-practices).
- [X] I confirm that this extension can be integrated to this GitHub repository, distributed and MIT licensed.

### Example

#

**Comment by Bouh** [comment]
@fedoric Hello you have to put the file by zipping it and drag&drop it here not copy-paste the raw content ;)

**Comment by Bouh** [comment]
Thank you @fedoric!
I see you added some `console.log()`.
What are the other change?
