### ISSUE TITLE
[Shake object extension] bug

### ISSUE THREAD

**Issue by VegeTato** [GDevelopApp/GDevelop-extensions#287]
![bugged](https://user-images.githubusercontent.com/81715237/141186788-25e21e86-153f-4764-9f04-21a833f83817.gif)

when the user shake the object, after the shake finish, it never goes back to the original X and Y positions of that object before it shakes, same thing with the rotation

1. install "Shake object extension"
2. events > shake object
3. Launch the game
4. X Y and angles is going back to rounding numbers (not the original exact number)

## Other details
* PC / Windows 10
* Desktop GDevelop, latest version released
* a simple fix to the extension would be to store the object X and Y and angles (using variables maybe) BEFORE it shakes
and after the shakes finish > call that variables back.

Example project:
[Shake object extension bug.zip](https://github.com/GDevelopApp/GDevelop-extensions/files/7515689/Shake.object.extension.bug.zip)

**Comment by tristanbob** [comment]
```
A simple fix to the extension would be to store the object X and Y and angles (using variables maybe)
 BEFORE it shakes and after the shakes finish > call that variables back.
```

That is sort of what it does.  If I only saved the original values and moved back to them, then an object could never move during a shake, because it would always be teleported back to the starting point.

Instead, I keep a variable of the amount of change that I add/subtract to position/scale/rotation.  When the shake is over, I apply the net value of that variable to the object.

**Comment by VegeTato** [comment]
> 
> 
> ```
> A simple fix to the extension would be to store the object X and Y and angles (using variables maybe)
>  BEFORE it shakes and after the shakes finish > call that variables back.
> ```
> 
> That is sort of what it does. If I only saved the original values and moved back to them, then an object could never move during a shake, because it would always be teleported back to the starting point.
> 
> Instead, I keep a variable of the amount of change that I add/subtract to position/scale/rotation. When the shake is over, I apply the net value of that variable to the object.
> 
> Perhaps this can be fixed by always rounding the amount that I add/subtract? If I ever get time, I'll test that solution first.

but your extension got timer in there (if the last option is set to No "Default no"), i don't understand what you mean by "the object will never move during the shake" why ? since there is a timer, Store the variables at the beginning of the scene, and when the timer finish, call the variables back, (during the timer it wont be called, so it should shake), well i don't know how you built it inside, but that's how i would fix it :3
