### ISSUE TITLE
New extension: <Car Movement>

### ISSUE THREAD

**Issue by Mrtubagames** [GDevelopApp/GDevelop-extensions#349]
### Description

This extension adds a car movement behavior

### How to use the extension

This extension can be usefull to make a racing game, or make a game where you can enter cars.

### Checklist

- [X] I've followed all of [the best practices](http://wiki.compilgames.net/doku.php/gdevelop5/extensions/best-practices).
- [X] I confirm that this extension can be integrated to this GitHub repository, distributed and MIT licensed.

### Example

[CarMovement.zip](https://github.com/GDevelopApp/GDevelop-extensions/files/7921734/CarMovement.zip)

### Extension file

[Car.zip](https://github.com/GDevelopApp/GDevelop-extensions/files/7921731/Car.zip)

**Comment by D8H** [comment]
Thank you for sharing an extension.

I think that people will expect a car movement extension to be more realistic. For instance, when a car turns it change the acceleration direction but it takes more time for the speed to change of direction and the car orientation might change according to drifting.

There is top-down car game example that use Physics extension:
* https://gdevelop-app.com/game-example/car-physics

Its physic is not great but it could be a good place to start.

These are open source top-down racing games if you need some references:
* https://github.com/juzzlin/DustRacing2D
* https://github.com/agateau/pixelwheels
* https://github.com/manuelbua/uracer-kotd

**Comment by arthuro555** [comment]
Hi @Mrtubagames 👋 

A review has started for this extension, but a new option has presented itself in the meantime. We now have a list of unreviewed "Community extensions", and your extension can be added to it, bypassing the review phase.

If you chose to *not take a review*, you need to keep the following in mind:

- As of now, community extensions are not yet shown to users, but they should be until next update
- Community extensions will never be shown to GDevelop users directly, they will have to check a checkbox for them to be shown
- All community extension have a warning about them being unstable and unreviewed displayed on their store page
- Your extension will be added immediately, no question asked, and without you needing to do any changes to your extension
- You will still need to make an extension that passes the bot's tests (meaning you still should respect the extension best practices)

tl;dr You will not need to do any more (or only minimal) work on your extension, but it might not meet the standards of all users, and reach less users.

If you chose to continue on with the review:

- The reviewing process might require of you to make some changes to your extension until it meets our reviewer's standards
- Your extension will reach more users
- You will be delivering a better extension to the community
- It will take a bit more time for your extension to be added to the store

tl;dr You will need to do a bit more work but deliver a high quality contribution that will reach more people


The choice is yours, please tell us how you would like to continue.

**Comment by arthuro555** [comment]
Closing as abandoned
