### ISSUE TITLE
Make it rain

### ISSUE THREAD

**Issue by VegeTato** [GDevelopApp/GDevelop-extensions#350]
### Description

![Make it rain extension](https://user-images.githubusercontent.com/81715237/125968534-c4ae65fd-ae2d-4996-97c3-1cb5ff621d7c.gif)
![Make it rain extension part2](https://user-images.githubusercontent.com/81715237/125968552-7195f576-8088-48db-8aff-b26fddc0be04.gif)

this extension is useful to make rain weather or just the rain effect on any object, also can help in colliding the rain with another object, it will add the life feeling to any kind of game

Version 0.1
------------------------------------
-User can select the object to rain
-User can select to rain object from a selected direction
-User can set condition to check if the rain object collides with another object
-User can set action to Stop/Start the rain object
-User can select object2 to rain object from it on a selected direction
-User can set an action to stop rain object from moving

Version 0.2
------------------------------------
-User have the option to select the rain direction from a list (Down/Up/Right/Left)
-Fixed a bug where stopping the rain action and resuming it would drop a rain out of range

Version 0.3
------------------------------------
-User can set the rain intensity
-Updated the example to more realistic rain effect when colliding with player

Version 0.4
------------------------------------
-Added the ability to change the rain angle
-Added the ability to change the rain animation after the collision and in the same condition Added the options to check Yes or No:
•Change rain object position to object surface?
•Remove rain object after it finish the animation?
•Remove rain object if it collides with the edges of the object?
•Stop rain object after collision with other object?
-Added an option to check Yes/No to delete the rain objects if its out of screen
-Fixed variables names
-Updated the example

Version 0.5
------------------------------------
-Fixed a bug in the Start/Stop rain actions
-Fixed few mistakes in the example
-Fixed few wrong sentences in the extension
-Added condition to restart scene if player is out of screen in the example
-Changed the parameter sentences
-Added few long descriptions
-Updated the example for the latest updates of the extension and changed the sprites as well for the best

### How to use the extension

**You can test the extension here:**
https://games.gdevelop-app.com/game-1af8241b-004d-4bae-bff0-f65600adefb4/index.html

### Checklist

- [X] I've followed all of [the best practices](http://wiki.compilgames.net/doku.php/gdevelop5/extensions/best-practices).
- [X] I confirm that this extension can be integrated to this GitHub repository, distributed and MIT licensed.

### Example

[Make it rain extension example V0.0.5.zip](https://github.com/GDevelopApp/GDevelop-extensions/files/7925430/Make.it.rain.extension.example.V0.0.5.zip)

### Extension file

[Make it rain extension V0.0.5.zip](https://github.com/GDevelopApp/GDevelop-extensions/files/7925432/Make.it.rain.extension.V0.0.5.zip)

**Comment by Bouh** [comment]
This raining extension should use the behavior but as we can't bind an object as parameters from a behavior let's go for the review:


- [ ] Try not to repeat the code by copying and pasting for each direction. For example, your "MakeItRain" function has a section for each direction (up, down, left, right). Only the angle should change depending on a variable.
- [ ] `Raining speed (in pixel)` pixel isn't a unit speed. `in pixels per second` is correct, same for the other functions, please use valid units.
- [ ] `Example: 10` if 10 is the value by default change `Example` by `Default`, same for the other functions.
- [ ] [ ] `Creaet rain object at zorder` typo
- [ ] Some parameters are in lowercase and some in PascalCase, can you change all these parameters in PascalCase as recommended in the best practices guide.
- [ ] Update the timers with the new timer from 5.0.126
- [ ] `Delete the rain objects when its out of the screen ?` Extra space at the end.
- [ ] `Setting this option to No, might reduce your game performance
(Recommended: Yes)` We don't recommend anything, we show the default value.
- [ ] `Use _PARAM1_ as a raining object at a speed of _PARAM2_ and direction _PARAM3_ (respawning in _PARAM4_, timer: _PARAM5_, layer: _PARAM6_, z-order: _PARAM7_, intensity: _PARAM8_, rain angle: _PARAM9_)`
rain angle: _PARAM9_ **in degrees**
- [ ] Abuse of copy-paste leaves some traces.
![image](https://user-images.githubusercontent.com/1670670/150802530-dc78ac43-e07d-4b41-a2d2-a8371d0b10fd.png)
- **StartRain** function, the layer argument doesn't exist in the parameters list but it's called in the create action. Same for **StartRainFromObject**, and maybe some others functions.
- **RainCollide** function use 4 loops on the same instance, this can be optimized to reduce to one loop.
- **RainCollide** function, the condition front of the delete actions can be wrapped in one event with a **or** condition.

I'll stop here, there are other things to say but overall it's still the same:
- Copy/paste code to reduce.
- Different syntaxes everywhere for parameter names.

Please check the buttons in the list above when you fixed the items.
