### ISSUE TITLE
MarchingSquares typo (trickness -> thickness)

### ISSUE THREAD

**Issue by tristanbob** [GDevelopApp/GDevelop-extensions#388]
There are 8 uses of the text "trickness", but I think they should be "thickness". If these were only text descriptions, I'd push the change without review.  

However, some of them are variable names in javascript, so I wanted @D8H to review them.

**Comment by D8H** [comment]
Where can I find the changes?

**Comment by Bouh** [comment]
@D8H @tristanbob  I started a PR for it 
https://github.com/GDevelopApp/GDevelop-extensions/pull/390
