### ISSUE TITLE
New Extension: Dash

### ISSUE THREAD

**Issue by Karl-Za-Great** [GDevelopApp/GDevelop-extensions#394]
### Description

This extension will add an dash action on a object with the behavior, with configurable speed, angle, the time in seconds where the object stops, cooldown(preferred values are from 0.1 to 5).

Online preview: [Dash preview](https://game-previews.gdevelop-app.com/1649984342618-76351/index.html).

### How to use the extension

Its useful for dungeon crawler games, action games, shooter games and more.
All you need is to import/install the extension, the add it to a sprite object use the "Dash" action.

### Checklist

- [X] I've followed all of [the best practices](http://wiki.compilgames.net/doku.php/gdevelop5/extensions/best-practices).
- [X] I confirm that this extension can be integrated to this GitHub repository, distributed and MIT licensed.

### Example

[Example.zip](https://github.com/GDevelopApp/GDevelop-extensions/files/8493888/Example.zip)

### Extension file

[Dash.zip](https://github.com/GDevelopApp/GDevelop-extensions/files/8493884/Dash.zip)

**Comment by Platricktsk** [comment]
hmm, ?

**Comment by arthuro555** [comment]
Hello @Astr0Cookie 👋 

Your extension has been marked for review, but a new option has presented itself in the meantime. We now have a list of unreviewed "Community extensions", and your extension can be added to it, bypassing the review phase.

If you chose to *not take a review*, you need to keep the following in mind:

- As of now, community extensions are not yet shown to users, but they should be until next update
- Community extensions will never be shown to GDevelop users directly, they will have to check a checkbox for them to be shown
- All community extension have a warning about them being unstable and unreviewed displayed on their store page
- Your extension will be added immediately, no question asked, and without you needing to do any changes to your extension
- You will still need to make an extension that passes the bot's tests (meaning you still should respect the extension best practices)

tl;dr You will not need to do any more (or only minimal) work on your extension, but it might not meet the standards of all users, and reach less users.

If you chose to continue on with the review:

- The reviewing process might require of you to make some changes to your extension until it meets our reviewer's standards
- Your extension will reach more users
- You will be delivering a better extension to the community
- It will take a bit more time for your extension to be added to the store

tl;dr You will need to do a bit more work but deliver a high quality contribution that will reach more people


The choice is yours, please tell us how you would like to continue.

**Comment by Astr0Cookie** [comment]
> 

I will choose to continue the reviewing process of this extension

**Comment by D8H** [comment]
Should it be renamed "TopDownDash"?

**Comment by Astr0Cookie** [comment]
> Should it be renamed "TopDownDash"?

Can be used with platfromers, i tried it

**Comment by arthuro555** [comment]
Since the previous post says that there is already an extension doing this, closing this now.
