### ISSUE TITLE
New extension: FadeObjects

### ISSUE THREAD

**Issue by thirrek** [GDevelopApp/GDevelop-extensions#404]
### Description

The FadeObjects extension allows users to fade in and out objects from a scene, to create a more proffesional feeling in the game. It works with any object, and i highly customizable.

### How to use the extension

The extension has two actions: `Fade in an object` and `Fade out an object`. To use an action you pick the object and set the time (how long it will take for the object to fade). The `Fade in an object` action also needs the X and Y position where the object will be created, and the layer to create the object at.

It is very easy and works with any object.

### Checklist

- [X] I've followed all of [the best practices](http://wiki.compilgames.net/doku.php/gdevelop5/extensions/best-practices).
- [X] I confirm that this extension can be integrated to this GitHub repository, distributed and MIT licensed.

### Example

https://drive.google.com/file/d/1R5zFvmg1LHl-uNBkhm7Mqny-_IbcOzpd/view?usp=sharing

### Extension file

https://drive.google.com/file/d/1UMOiMUoBUjomYg09S1k6LLL61gDD0Maj/view?usp=sharing

**Comment by arthuro555** [comment]
Please actually upload the zip file directly through github, don't use a google drive link.

**Comment by arthuro555** [comment]
Hello @thirrez 👋 

Your extension has been marked for review, but a new option has presented itself in the meantime. We now have a list of unreviewed "Community extensions", and your extension can be added to it, bypassing the review phase.

If you chose to *not take a review*, you need to keep the following in mind:

- As of now, community extensions are not yet shown to users, but they should be until next update
- Community extensions will never be shown to GDevelop users directly, they will have to check a checkbox for them to be shown
- All community extension have a warning about them being unstable and unreviewed displayed on their store page
- Your extension will be added immediately, no question asked, and without you needing to do any changes to your extension
- You will still need to make an extension that passes the bot's tests (meaning you still should respect the extension best practices)

tl;dr You will not need to do any more (or only minimal) work on your extension, but it might not meet the standards of all users, and reach less users.

If you chose to continue on with the review:

- The reviewing process might require of you to make some changes to your extension until it meets our reviewer's standards
- Your extension will reach more users
- You will be delivering a better extension to the community
- It will take a bit more time for your extension to be added to the store

tl;dr You will need to do a bit more work but deliver a high quality contribution that will reach more people


The choice is yours, please tell us how you would like to continue.

**Comment by arthuro555** [comment]
Since there was no response, this submission is considered abandoned and will be closed. Please make a new submission if you want to submit this extension.
