### ISSUE TITLE
New extension: Music distance synchronize

### ISSUE THREAD

**Issue by Siddharth9ig** [GDevelopApp/GDevelop-extensions#432]
### Description

It is used to synchronize music volume with distance between objects. Lower with greater distance and higher with lesser distance.

### How to use the extension

It is used to synchronize music volume with distance between objects. Lower with greater distance and higher with lesser distance.
You need a music playing on a channel and two objects for example player and river.

### Checklist

- [X] I've followed all of [the best practices](http://wiki.compilgames.net/doku.php/gdevelop5/extensions/best-practices).
- [X] I confirm that this extension can be integrated to this GitHub repository, distributed and MIT licensed.

### Example

[Uploading My project10.zip…]()

### Extension file

[Music_distance_synchronise.zip](https://github.com/GDevelopApp/GDevelop-extensions/files/8641377/Music_distance_synchronise.zip)

**Comment by HelperWesley** [comment]
Can you please resend the project file. Trying to look in to this one.
