### ISSUE TITLE
New extension: Fake 3D

### ISSUE THREAD

**Issue by ghostcl4y** [GDevelopApp/GDevelop-extensions#449]
### Description

This extension uses ZOrder as an Z axis

### How to use the extension

1. Install 3D extension
2. Open object behaviours
3. Add new behaviour
4. Now the object will be generated as 3D object. There are also some conditions and actions

### Checklist

- [X] I've followed all of [the best practices](http://wiki.compilgames.net/doku.php/gdevelop5/extensions/best-practices).
- [X] I confirm that this extension can be integrated to this GitHub repository, distributed and MIT licensed.

### Example

https://gamejolt.com/games/3d-gdevelop/723513

### Extension file

https://gamejolt.com/games/3d-gdevelop/723513

**Comment by VegeTato** [comment]
Hello :3
Cool extension, it seems fun to play around with it.
here is a few things that's required for the extension:

1- An example(Gdevelop project) is required to see how this extension work in action.
2- Rename action (Create an 3D object) to (Create 3D object) or (Create a 3D object).
3- Rename action (Add force in 3D) to (Add 3D force to object).
4- If you set the speed on Z axis to -5 or -1 (just any minus number) ,and then previewed the game, the object will disappear until you release the key (set as condition to add the force) then it will appear again.
5- the action (Create 3D object) doesn't seem to work, i set at the beginning of the scene to create and object at the center of the scene window, but nothing happened.
6- I don't think changing the object size to its Z order is a good idea.
7- (Z position) we already have a condition (Z order) to check the Z order of the object, its better to use it on creating another one.
8- (3D collision) ^ Same thing apply on the collision condition.
9- Rather on adding an event to check if the Object z order is less > than 2 then change it to 2
You can prevent the action (change object size set to its Z order) from happening if the Z order is less than 2
by setting a condition (Z order of Object is Greater than 2

Over all the extension have potentials but its still in a very basic position and require a lot of updates and improvements :3
Thanks for submitting it and we hope to have more extensions from you in the future 😉
