### ISSUE TITLE
Found bug on sentence event sheet while fiddling around linktools extension

### ISSUE THREAD

**Issue by planktonfun** [GDevelopApp/GDevelop-extensions#460]
## Describe the bug of the extension
LinkTools extension
Error in the sentence in events sheet

- [x] Please double check that the bug is not already reported in the issues list.

## To Reproduce
1. Install extension linktools
2. Go to Editor
3. Check functions linkrectangularneighbors, linkisometricrectangularneighbors, canreachwithmaxweight

* Please include a link to a game if possible!
No link, I was trying to figure out how it works

* If applicable, add screenshots to help explain your problem.
Screenshots:
![image](https://user-images.githubusercontent.com/1837825/173873219-6abcfafb-2c09-4787-92ca-ff5d10b256b5.png)
![image](https://user-images.githubusercontent.com/1837825/173873525-65b7235a-bc0a-4b6f-ba94-0882475a4b0d.png)
![image](https://user-images.githubusercontent.com/1837825/173873558-160e1a2d-d151-4b8d-af65-0c4fa7402a3a.png)

## Other details
* OS is windows 10
* Gdevelop version 4.0.99-0-release

**Comment by D8H** [comment]
The sentences are already very long. Some parameters with lesser importance are not shown in the event sheet to keep it readable.
