### ISSUE TITLE
DraggableSliderControl different descriptions

### ISSUE THREAD

**Issue by planktonfun** [GDevelopApp/GDevelop-extensions#484]
## Describe the bug of the extension
DraggableSliderControl 
I was using it and noticed opposite results, I think the descriptions are mixed

- [x] Please double check that the bug is not already reported in the issues list.

## To Reproduce
1. Install DraggableSliderControl Extension
2. Click extension
3. Click Open in editor
4. Check descriptions

* Please include a link to a game if possible!
* If applicable, add screenshots to help explain your problem.
![image](https://user-images.githubusercontent.com/1837825/177021147-67088b6f-1d20-4b39-b125-48759be30ea0.png)
![image](https://user-images.githubusercontent.com/1837825/177021149-d58acd70-30e5-4798-b47f-931ef5db552e.png)

## Other details
* Include any OS/browser version/smartphone that you're using
Windows 10, Chrome
* Which version of GDevelop are you using? The desktop app or the web-app?
Desktop
* Add any other context about the problem here.

**Comment by D8H** [comment]
I open this PR to reduce the risk of these kind of mistake:
* https://github.com/4ian/GDevelop/pull/4083

**Comment by tristanbob** [comment]
This is fixed here: https://github.com/GDevelopApp/GDevelop-extensions/pull/541
