### ISSUE TITLE
Update: Added an expression to get maximum health and an action to change it.

### ISSUE THREAD

**Issue by Mixen-me** [GDevelopApp/GDevelop-extensions#490]
### Description

The following were added:
- Added an action to change the maximum health of the object.
- Added an expression to get the maximum health.

### Checklist

- [X] I've followed all of [the best practices](http://wiki.compilgames.net/doku.php/gdevelop5/extensions/best-practices).
- [X] I confirm that this extension can be integrated to this GitHub repository, distributed and MIT licensed.
- [X] I am aware that the extension may be updated by anyone, and do not need my explicit consent to do so.

### What tier of review do you aim for your extension?

Reviewed

### Example file

[HealthXyz.zip](https://github.com/GDevelopApp/GDevelop-extensions/files/9102079/HealthXyz.zip)

### Extension file

[Health.zip](https://github.com/GDevelopApp/GDevelop-extensions/files/9101961/Health.zip)

**Comment by tristanbob** [comment]
I have created a PR for this.  Once it is approved it will be merged and active.

https://github.com/GDevelopApp/GDevelop-extensions/pull/523
