### ISSUE TITLE
NumberShortener

### ISSUE THREAD

**Issue by GingerSniper10** [GDevelopApp/GDevelop-extensions#503]
### Description

This extension turns large, unwieldy numbers into smaller, more concise ones, e.g 1,000 into 1K or 1,000,000 into 1M.

### How to use the extension

Firstly, you need to make a variable to store the unchanged large numbers, and then enter this variable into the first parameter box. Second, you need to create either a text, BBtext or BitMap text object as your output, and enter that into the second parameter box. Make sure that you choose the correct function for the output type, because otherwise it won't work. If all the steps have been followed, the extension should be working fine, and all your large numbers in the variable will be displayed in a more concise way in your output object!

### Checklist

- [X] I've followed all of [the best practices](http://wiki.compilgames.net/doku.php/gdevelop5/extensions/best-practices).
- [X] I confirm that this extension can be integrated to this GitHub repository, distributed and MIT licensed.
- [X] I am aware that the extension may be updated by anyone, and do not need my explicit consent to do so.

### What tier of review do you aim for your extension?

Community (Unreviewed)

### Example file

[ExtensionExample.zip](https://github.com/GDevelopApp/GDevelop-extensions/files/9168349/ExtensionExample.zip)

### Extension file

[NumberShortener.zip](https://github.com/GDevelopApp/GDevelop-extensions/files/9168591/NumberShortener.zip)

**Comment by DaddyPluM** [comment]
Yo
Remove the dot at the end of the parameters
Add a dot at the end of the extension description

**Comment by MudkipWorld** [comment]
Hi, I tried using this extension (downloaded it from here), but it doesn't want to work. I tried downloading the example file, but it was an export of HTML5 (from what I could tell). Would you mind try editing it so it work? (or make the example file a normal json that can be opened in Gdevelop.

Thanks for reading.

**Comment by MudkipWorld** [comment]
(I unintentionally deleted the original comment)
I can't get the extension to work and the example file can't be opened with Gdevelop. Could you provide one that can be opened for reference?

Thanks for reading.

**Comment by ZeroSupply2** [comment]
the one that guy uploaded is broken now.
cuz ig gdevelop developers (sounds funny) fixed some shit and etc.
i made the fixed version.
[NumberShortener.zip](https://github.com/GDevelopApp/GDevelop-extensions/files/12357678/NumberShortener.zip)

**Comment by ZeroSupply2** [comment]
the one that guy uploaded is broken now.
cuz ig gdevelop developers (sounds funny) fixed some shit and etc.
i made the fixed version.
(the actually one) (now it uses ceilTo for normal numbers, tens and hundreds) (and im sorry for spamming)
[NumberShortenerFixed+CeilTo.zip](https://github.com/GDevelopApp/GDevelop-extensions/files/12358534/NumberShortenerFixed%2BCeilTo.zip)

**Comment by arthuro555** [comment]
@ZeroSupply2 Please make a new submission for your extension.

Since multiple reports have been made that the extension does not work, GingerSniper's submission will be closed.
