### ISSUE TITLE
New extension: Melee Slash System

### ISSUE THREAD

**Issue by DelltDev** [GDevelopApp/GDevelop-extensions#509]
### Description

melee system like genshin impact (yes i play geshin impact)

### **You need the Tween Behavior And Stick Behavior in the Weapon Sprite**
if someone modify or help the extension i will be greatful
discord to help me: DustLol#7350

### How to use the extension

simple add the Melee Behavior (MeleeSystem) and add a Action "Attack", fill in the requirements and vwala, it's work it, if you have an issue, dm me on discord

### Checklist

- [X] I've followed all of [the best practices](http://wiki.compilgames.net/doku.php/gdevelop5/extensions/best-practices).
- [X] I confirm that this extension can be integrated to this GitHub repository, distributed and MIT licensed.
- [X] I am aware that the extension may be updated by anyone, and do not need my explicit consent to do so.

### What tier of review do you aim for your extension?

Community (Unreviewed)

### Example file

[Sword Slash Example.zip](https://github.com/GDevelopApp/GDevelop-extensions/files/9177163/Sword.Slash.Example.zip)
 

### Extension file

[MeleeSlash.zip](https://github.com/GDevelopApp/GDevelop-extensions/files/9177164/MeleeSlash.zip)

**Comment by arthuro555** [comment]
@DelltDev You never addressed the issues raised by the bot. Are you still willing to submit your extension? If we do not hear from you, we'll assume you have abandoned the extension and close the submission. Otherwise, please follow the bots instructions or create a new submission.
