### ISSUE TITLE
BoidsMovement problem when scene changes

### ISSUE THREAD

**Issue by OutOfCopper** [GDevelopApp/GDevelop-extensions#525]
## Describe the bug of the extension
BoidsMovement
Extension breaks and freezes the scene you are on when **switching** to a scene for the second time, (example: Going from a 'title scene' to 'game scene' and then either restarting the 'game scene' you were on, **or** then going back to 'title scene' and back to 'game scene') that has an instance of an object with BoidsMovement in the scene.

Also, the extension freezes when spawning an object with BoidsMovement and **then switching** to another scene or the same scene (that doesn't have an object with Boids at the very start because if it did it would freeze the current scene) and trying to spawn another object that has BoidsMovement.

## To Reproduce
1. Make one or two scenes
2. Install BoidsMovement Extension
3. Make an object with BoidsMovement Extension
4. Place the object in a scene
5. Add an event to change the scene (like R key is released), if you made two scenes make the events to switch between them
6. Preview the game
7. Start/switch scenes. The preview should freeze

* Please include a link to a game if possible!
[BoidMovementIssue.zip](https://github.com/GDevelopApp/GDevelop-extensions/files/9247158/BoidMovementIssue.zip)
https://liluo.io/games/7e4fcf29-59d9-4fc1-ac18-5b7cba56a3a6 (After the game freezes, you have to refresh the page)

___
[SubdividedCompanion.zip](https://github.com/GDevelopApp/GDevelop-extensions/files/9247250/SubdividedCompanion.zip)

I didn't plan on including this file on the original project that I found the issue on, but after creating a new Gdev project and getting slightly different results I think it's best I include "SubdividedCompanion." The extension breaks but doesn't freeze when spawning an object with BoidsMovement and **then switching** to another scene or the same scene (that doesn't have an object with Boids at the start because if it did it would freeze the current scene) and trying to spawn another object that has BoidsMovement. Spawning at that point looks like the object spawns at 0,0 and doesn't move.

## Other details
* Using Gdevelop 5.0.139 desktop app
* Happens on any browser version of Gdevelop (also any other computer)
* Problem still persists if you delete and/or disable the objects with BoidsMovement before switching scenes
* You can still pause and resume scenes without anything breaking/freezing

**Comment by D8H** [comment]
Thank you for reporting this. I submitted a fix. Tell me if it works for you.

Thanks Tristan, I never look in the issues of extensions.
