### ISSUE TITLE
Easy Sprite Button Maker

### ISSUE THREAD

**Issue by GameDevPassion** [GDevelopApp/GDevelop-extensions#540]
### Description

This extension changes your sprites depending on weather you hover over them or press them.
Easy event conditions: find out weather a sprite is clicked or being pressed.

The extension is fully customizable!
Define how much the button moves when clicked, weather it changes animation when clicked, if it responds only to Left mouse clicks or other Mouse clicks etc. ...
And you can change all settings inside the event sheet!

Features include:

-Super easy and intuitive: install the behavior and you already have a usable button!
-Set draggable clicks on/off
-set hover/pressed animations
-set how much the button moves up/down when hovering/pressing
-deactivate all button events
-deactivate button animations while the button keeps responding to clicks

### How to use the extension

You install the behavior on a sprite, and you can immediately set the parameters.

You can change all parameters inside the event sheet as well.

### Checklist

- [X] I've followed all of [the best practices](http://wiki.compilgames.net/doku.php/gdevelop5/extensions/best-practices).
- [X] I confirm that this extension can be integrated to this GitHub repository, distributed and MIT licensed.
- [X] I am aware that the extension may be updated by anyone, and do not need my explicit consent to do so.

### What tier of review do you aim for your extension?

Reviewed

### Example file

[MyExample.zip](https://github.com/GDevelopApp/GDevelop-extensions/files/9366738/MyExample.zip)

### Extension file

[MyExtension.json.zip](https://github.com/GDevelopApp/GDevelop-extensions/files/9366743/MyExtension.json.zip)

**Comment by tristanbob** [comment]
@GameDevPassion thank you so much for taking the time to submit an extension!  We are always looking for people like you to help make GDevelop better.  I hope you will keep creating and contributing.  Let me know if you have any questions about how/what to work on.

Regarding this extension, there is already submitted PR (https://github.com/GDevelopApp/GDevelop-extensions/pull/495) for a button behavior that provides this functionality, so I am going to close this one. 

One thing that you will want to fix in your games is to make sure that the clicks "start" inside the object.  You can do it like this:

```
Button is down
TriggerOnce
--------> Cursor is on object
```

**Comment by GameDevPassion** [comment]
Hello tristanbob,

the extension you linked has nothing to do with my button extension.
It is a state machine. I don't want to use that extension method, it's too complicated and time consuming.
It doesn't create automatic buttons that are fully functionable and customizable the way mine does.
In my extension you immediately know if a button is clicked or pressed and it animates automatically.
You don't have to set it up for 10 minutes in the event editor.
Please I want it in the Gdevelop editor for my own ease when I create buttons.
Buttons should be simple and fast to create, so not like the state machine you linked.
I tried it out, and it even says, it's a state machine, not a button extension.

In my extension you can choose weather the click starts inside or outside the button via the "dragging click" option.
So I'm not sure I'm able to follow what you mean that the clicks start inside the object only. It does in my extension.
Did you try out my latest extension submission? I tried multiple times because it seemed buggy and I got error messages.

**Comment by tristanbob** [comment]
@GameDevPassion based on your response I will re-open this issue so it can be evaluated further.  I agree that we need to make an easier way to make buttons in GDevelop!

**Comment by GameDevPassion** [comment]
Thank you very much.

I would further build out this extension, if I know that it could be integrated into the app.
Further plans would be to make the button behavior available for text and tiled sprite objects.
And potentially add sounds. The only way to add sounds would be to let the user enter the sound file path as a string and then play it with javascript, so it remains to see wether that's useful.

**Comment by GameDevPassion** [comment]
I realize that you can access community extensions from Gdevelop. That's all I actually wanted.
I will submit this again as a community submission.
Thanks.
