### ISSUE TITLE
Update: RenderToSprite.

### ISSUE THREAD

**Issue by VanCastar** [GDevelopApp/GDevelop-extensions#604]
### Description

Updating Arthuro555:s Extension of RenderToSprite.

I added a new function "RenderSceneArea" to be able to render desired area of a scene to a sprite.

Fixed some wording in the descriptions too.

### How to use the extension

In addition to the functionality of the previous version.

You can now set an origin point X,Y with Width and Height to capture a desired area of a scene to render to sprite.

### Checklist

- [X] I've followed all of [the best practices](http://wiki.compilgames.net/doku.php/gdevelop5/extensions/best-practices).
- [X] I confirm that this extension can be integrated to this GitHub repository, distributed and MIT licensed.
- [X] I am aware that the extension may be updated by anyone, and do not need my explicit consent to do so.

### What tier of review do you aim for your extension?

Reviewed

### Example file

[DemoingRenderToSprite.zip](https://github.com/GDevelopApp/GDevelop-extensions/files/9657234/DemoingRenderToSprite.zip)

### Extension file

[RenderToSprite.zip](https://github.com/GDevelopApp/GDevelop-extensions/files/9657239/RenderToSprite.zip)

**Comment by tristanbob** [comment]
I've updated this issue to show this is an Extension Update.  I assigned @arthuro555 since he created the original version, but if he is not available then anyone can look at this.
