### ISSUE TITLE
Update : MultitouchJoystick

### ISSUE THREAD

**Issue by jerikothomas** [GDevelopApp/GDevelop-extensions#629]
### Description

Updating VictrisGames, AstroCookie Extension MultitouchJoystick.

Added 8-way movement (45° arc)
![Peek 2022-10-06 21-57](https://user-images.githubusercontent.com/20714832/194347655-e158ec70-fee3-4838-99cc-17a5d5347c5a.gif)

### How to use the extension

To use the 8-way movement, simply select "MultitouchJoystick8Way" in behaviors tab of the joystick outer

1. Add new behavior to the Joystick object and select "MultitouchJoystick8Way"
  
![AddBehaviour](https://user-images.githubusercontent.com/20714832/194349792-1caed8c4-0c1a-4886-ac66-c34c52979031.gif)

2. Using direction condition in the Event Sheet 
![EventSheet](https://user-images.githubusercontent.com/20714832/194349861-cbc4775d-0b76-4d80-9b54-cd92d5b3af66.gif)

### Checklist

- [X] I've followed all of [the best practices](http://wiki.compilgames.net/doku.php/gdevelop5/extensions/best-practices).
- [X] I confirm that this extension can be integrated to this GitHub repository, distributed and MIT licensed.
- [X] I am aware that the extension may be updated by anyone, and do not need my explicit consent to do so.

### What tier of review do you aim for your extension?

Community (Unreviewed)

### Example file

[ExampleFile8WayTouch.zip](https://github.com/GDevelopApp/GDevelop-extensions/files/9725883/ExampleFile8WayTouch.zip)

### Extension file

[MultitouchJoystick.json.zip](https://github.com/GDevelopApp/GDevelop-extensions/files/9725885/MultitouchJoystick.json.zip)

**Comment by jerikothomas** [comment]
->Example File 
[ExampleFile8WayTouch.zip](https://github.com/GDevelopApp/GDevelop-extensions/files/9730756/ExampleFile8WayTouch.zip)

->Extension File
[MultitouchJoystick.json.zip](https://github.com/GDevelopApp/GDevelop-extensions/files/9730759/MultitouchJoystick.json.zip)

How to use

- Add behavior to the Joystick object
 ![AddBehaviour](https://user-images.githubusercontent.com/20714832/194471126-5162f034-98be-404c-a2f5-d1de5507b237.gif)

- Select Joystick pushed in a direction (8-way movement) in event sheet condition
![EventSheet](https://user-images.githubusercontent.com/20714832/194471390-a6dee216-a63f-4f91-b902-b233bdaae5b9.gif)

**Comment by Bouh** [comment]
!update [MultitouchJoystick.json.zip](https://github.com/GDevelopApp/GDevelop-extensions/files/9730759/MultitouchJoystick.json.zip)

**Comment by tristanbob** [comment]
@jerikothomas this looks really good!  I haven't tested it, but here are a few changes I recommend:

- Add yourself as an author
- Increment version from 1.0.1 to 1.1.0 (since we are adding new functionality)
- For maximum clarity, the original function should include this text `Joystick pushed in a direction (4-way movement)`

**Comment by jerikothomas** [comment]
[MultitouchJoystick.json.zip](https://github.com/GDevelopApp/GDevelop-extensions/files/9738526/MultitouchJoystick.json.zip)

- Added new author
- Increase version to 1.1.0
- Rename `Joystick pushed in a direction` to `Joystick pushed in a direction (4-way movement)`

**Comment by tristanbob** [comment]
@jerikothomas congrats, this change is now live in the app! https://github.com/GDevelopApp/GDevelop-extensions/pull/641

If you are looking to earn some extra credit, would you be interested in adding these same conditions to the gamepad extension also?  :)

**Comment by jerikothomas** [comment]
> @jerikothomas congrats, this change is now live in the app! #641
> 
> If you are looking to earn some extra credit, would you be interested in adding these same conditions to the gamepad extension also? :)

sure if i got time to do it, i will mention it to you
