### ISSUE TITLE
Flash Color & Flash Extension Fixes

### ISSUE THREAD

**Issue by Entr0py404** [GDevelopApp/GDevelop-extensions#656]
### Description

The Flash Color extension adds a behavior to make a sprite object flash in a color.
Flash extension fixes: timer order, updated from deprecated method.

### How to use the extension

Behavior to make a sprite object flash in a color.
Fixes flash extinction timings and updated timer events

### Checklist

- [X] I've followed all of [the best practices](http://wiki.compilgames.net/doku.php/gdevelop5/extensions/best-practices).
- [X] I confirm that this extension can be integrated to this GitHub repository, distributed and MIT licensed.
- [X] I am aware that the extension may be updated by anyone, and do not need my explicit consent to do so.

### What tier of review do you aim for your extension?

Reviewed

### Example file

[Flash Color Extension Example.zip](https://github.com/GDevelopApp/GDevelop-extensions/files/9941515/Flash.Color.Extension.Example.zip)

### Extension file

[FlashColor.zip](https://github.com/GDevelopApp/GDevelop-extensions/files/9941518/FlashColor.zip)
[Flash.zip](https://github.com/GDevelopApp/GDevelop-extensions/files/9941519/Flash.zip)

**Comment by tristanbob** [comment]
Thanks @Entr0py404! 
This work has been implemented in this PR: https://github.com/GDevelopApp/GDevelop-extensions/pull/955
