### ISSUE TITLE
Play sound file dynamically from file or URL

### ISSUE THREAD

**Issue by lojik-ng** [GDevelopApp/GDevelop-extensions#664]
### Description

Allows you to dynamically preload and/or play sound from url or file path. 
Also supports loading sound from a text variable.
Can preload multiple audio files from the web or file.
Tested with browser based games.

### How to use the extension

Simply specify relative file path or audio file url as text or variable.

### Checklist

- [X] I've followed all of [the best practices](http://wiki.compilgames.net/doku.php/gdevelop5/extensions/best-practices).
- [X] I confirm that this extension can be integrated to this GitHub repository, distributed and MIT licensed.
- [X] I am aware that the extension may be updated by anyone, and do not need my explicit consent to do so.

### What tier of review do you aim for your extension?

Reviewed

### Example file

[playsound.zip](https://github.com/GDevelopApp/GDevelop-extensions/files/9995748/playsound.zip)

### Extension file

[PlaySound.json.zip](https://github.com/GDevelopApp/GDevelop-extensions/files/9995749/PlaySound.json.zip)

**Comment by arthuro555** [comment]
@DelltDev You never addressed the issues raised by the bot. Are you still willing to submit your extension? Since we did not not hear from you, we'll assume you have abandoned the extension and close the submission. Please follow the bots instructions and create a new submission.
