### ISSUE TITLE
PlaySound

### ISSUE THREAD

**Issue by lojik-ng** [GDevelopApp/GDevelop-extensions#676]
### Description

Preload and play dynamically loaded sound.
Allows you to preload and/or play sound from dynamic url or file path. 
Also supports loading sound from a string variable.
Can preload multiple dynamic sound files from the web or file.
Can queue dynamic sound files for playing sequentially like a playlist.
Tested with browser based games.

### How to use the extension

Available Actions are:
PreloadSoundFromPath.
PlaySoundFromPath.
PlaylistFromPath.
StopSoundFromPath.
SoundIsPlaying.

### Checklist

- [X] I've followed all of [the best practices](http://wiki.compilgames.net/doku.php/gdevelop5/extensions/best-practices).
- [X] I confirm that this extension can be integrated to this GitHub repository, distributed and MIT licensed.
- [X] I am aware that the extension may be updated by anyone, and do not need my explicit consent to do so.

### What tier of review do you aim for your extension?

Community (Unreviewed)

### Example file

[Uploading playsound.zip…]()

### Extension file

[PlaySound.json.zip](https://github.com/GDevelopApp/GDevelop-extensions/files/10123521/PlaySound.json.zip)

**Comment by arthuro555** [comment]
@lojik-ng You never addressed the issues raised by the bot. Are you still willing to submit your extension? Since we did not not hear from you, we'll assume you have abandoned the extension and close the submission. Please follow the bots instructions and create a new submission.
