### ISSUE TITLE
New extension: High Jump!!!

### ISSUE THREAD

**Issue by SonicForcesSucks** [GDevelopApp/GDevelop-extensions#688]
### Description

This will set the player jumps as strong as you want.(You can edit it from the behavior configuration)

### How to use the extension

You add the behavior to the player and go to the event sheet and write code:High Jump.

### Checklist

- [ ] I've followed all of [the best practices](http://wiki.compilgames.net/doku.php/gdevelop5/extensions/best-practices).
- [ ] I confirm that this extension can be integrated to this GitHub repository, distributed and MIT licensed.
- [ ] I am aware that the extension may be updated by anyone, and do not need my explicit consent to do so.

### What tier of review do you aim for your extension?

Community (Unreviewed)

### Example file

*none

### Extension file

[HighJumpExtension.zip](https://github.com/GDevelopApp/GDevelop-extensions/files/11011120/HighJumpExtension.zip)

**Comment by SonicForcesSucks** [comment]
ok

**Comment by SonicForcesSucks** [comment]
ok

**Comment by arthuro555** [comment]
Your version number must respect semantic versioning: it must be in the form of `<number>.<number>.<number>`. This allows us to tell the user when updating the extension whether there is a breaking change or not thanks to the semantic of this versioning system. In you case, you likely want `1.0.0` as version number: let me change that for you now.

**Comment by arthuro555** [comment]
@SonicForcesSucks You never addressed the new issues raised by the bot. Are you still willing to submit your extension? Since we did not not hear from you, we'll assume you have abandoned the extension and close the submission. Please follow the bots instructions and create a new submission.
