### ISSUE TITLE
Debug Extension

### ISSUE THREAD

**Issue by RamPlayzTheEpic** [GDevelopApp/GDevelop-extensions#707]
### Description

This extension allows you to debug items

### How to use the extension

If the object you set did not spawn twice then, First, Check if you have the function debug. Else, the sprite is broken

### Checklist

- [X] I've followed all of [the best practices](http://wiki.compilgames.net/doku.php/gdevelop5/extensions/best-practices).
- [X] I confirm that this extension can be integrated to this GitHub repository, distributed and MIT licensed.
- [X] I am aware that the extension may be updated by anyone, and do not need my explicit consent to do so.

### What tier of review do you aim for your extension?

Reviewed

### Example file

[Debug.zip](https://github.com/GDevelopApp/GDevelop-extensions/files/10328769/Debug.zip)

### Extension file

[DebugExtension.zip](https://github.com/GDevelopApp/GDevelop-extensions/files/10328775/DebugExtension.zip)

**Comment by RamPlayzTheEpic** [comment]
[DebugExtension.zip](https://github.com/GDevelopApp/GDevelop-extensions/files/10328775/DebugExtension.zip)

**Comment by arthuro555** [comment]
@RamPlayzTheEpic The bot is not very intelligent, it can only read your original post ;) You need to edit your original submission post to replace the old link with the new one for the submission process to carry on. I'll do it for you now.

**Comment by arthuro555** [comment]
@RamPlayzTheEpic You never addressed the new issues raised by the bot. Are you still willing to submit your extension? Since we did not not hear from you, we'll assume you have abandoned the extension and close the submission. Please follow the bots instructions and create a new submission.
