### ISSUE TITLE
canon

### ISSUE THREAD

**Issue by nightfallyt** [GDevelopApp/GDevelop-extensions#724]
### Description

for make bullet

### How to use the extension

just put the behavour "bullet" on a sprite and go to the code for make your bullet!
if you want make cooldown its posible!!

### Checklist

- [X] I've followed all of [the best practices](http://wiki.compilgames.net/doku.php/gdevelop5/extensions/best-practices).
- [X] I confirm that this extension can be integrated to this GitHub repository, distributed and MIT licensed.
- [X] I am aware that the extension may be updated by anyone, and do not need my explicit consent to do so.

### What tier of review do you aim for your extension?

Community (Unreviewed)

### Example file

[canon.zip](https://github.com/GDevelopApp/GDevelop-extensions/files/10401291/canon.zip)

### Extension file

[canon.zip](https://github.com/GDevelopApp/GDevelop-extensions/files/11011102/canon.zip)

**Comment by arthuro555** [comment]
As the bot's message outlined, please use an uppercase character for the first letter of your extension name. I'll do it for you now, but please do it yourself in the future.

**Comment by tristanbob** [comment]
What functionality does this extension provide?

**Comment by arthuro555** [comment]
@nightfallyt You never addressed the new issues raised by the bot. Are you still willing to submit your extension? Since we did not not hear from you, we'll assume you have abandoned the extension and close the submission. Please follow the bots instructions and create a new submission.
