### ISSUE TITLE
Slider duplicate

### ISSUE THREAD

**Issue by PascalLadalle** [GDevelopApp/GDevelop-extensions#751]
![image](https://user-images.githubusercontent.com/25978830/215274126-c60d1c71-d6da-4585-a818-6ddcd9939a8e.png)
There are two extensions. The most recent one doesn't have the description that the older one has.

![image](https://user-images.githubusercontent.com/25978830/215274246-c67d1a11-a439-4815-aa4b-c6388f1d5b25.png)
![image](https://user-images.githubusercontent.com/25978830/215274318-b6979551-838e-425e-b0cf-743d940fe4b6.png)

**Comment by PascalLadalle** [comment]
I ended up using the older one, as I never found how to get the recent one working... It doesn't show in the available behaviors for sprites, panel sprites, shape painters. 😕

**Comment by 4ian** [comment]
Indeed, we have these two extensions and we should rename the old one so that it's "deprecated".
As for the new one, you'll find it here ;)
<img width="929" alt="image" src="https://user-images.githubusercontent.com/1280130/215320954-a0320213-3f44-482e-9308-111c648fc09e.png">

We'll progressively deprecate the "objects made using shape painter behavior" in favor of these new objects ;)

**Comment by D8H** [comment]
The extensions are renamed:
- https://github.com/GDevelopApp/GDevelop-extensions/pull/755

**Comment by 4ian** [comment]
Closing this then!

**Comment by PascalLadalle** [comment]
Now I remember seeing this... in the release notes, I guess.
But the changes still don't explain how to use the new extension.
The older one has a nice 'how to' and 'tips'. The new one has nothing, yet the "workflow" is completely different from what we're used to. 😕 
The extension is called "PanelSpriteSlider", so one wants to add it to a panel sprite.
Also, I looked at the settings for the new object, there's so many of them... And you expect people to know what a "thumb" is?
The wiki link next to thumb redirects to the Panel Sprite page. 🤔 
The older extension has a video link that explains the term, iirc.
At least, add some basic description on how to use the extension. "Add a slider object to your scene to allow your players to select a numerical value by dragging a sprite (thumb) along a bar"... or something. 🤷

**Comment by D8H** [comment]
We wrote a new documentation yesterday:
https://wiki.gdevelop.io/gdevelop5/objects/multitouch-joystick

> The wiki link next to thumb redirects to the Panel Sprite page.

This is because it is a panel sprite configuration, but Florian removed it for the next released:
- https://github.com/4ian/GDevelop/commit/b09e783b06d319b3747766b298f558b97ffeb0da
