### ISSUE TITLE
New Extension: ReplaceLetterfromString

### ISSUE THREAD

**Issue by Marcboss1** [GDevelopApp/GDevelop-extensions#784]
### Description

This Extension allows you to replace **a** letter from a String with another letter.

### How to use the extension

If you want to replace **one** letter from a String with another with this Extension String you can.

### Checklist

- [ ] I've followed all of [the best practices](http://wiki.compilgames.net/doku.php/gdevelop5/extensions/best-practices).
- [ ] I confirm that this extension can be integrated to this GitHub repository, distributed and MIT licensed.
- [ ] I am aware that the extension may be updated by anyone, and do not need my explicit consent to do so.

### What tier of review do you aim for your extension?

Reviewed

### Example file

[My project51.zip](https://github.com/GDevelopApp/GDevelop-extensions/files/10734948/My.project51.zip)

### Extension file

[ReplaceLetterFromString.1.0.6.json(1).zip](https://github.com/GDevelopApp/GDevelop-extensions/files/12738826/ReplaceLetterFromString.1.0.6.json.1.zip)

**Comment by arthuro555** [comment]
@Marcboss1 Your extension file name must be the same as your extension ;) I'll remove the ` 1.0.6` from it for you, but be aware of this next time you submit an extension!
