### ISSUE TITLE
Timers

### ISSUE THREAD

**Issue by cubestudioss** [GDevelopApp/GDevelop-extensions#786]
### Description

2 New Timers That Can Count Up And Down For Speed Running And Whatever

### How to use the extension

(You Are Going To Need A Text Object)

You Make A New Event And Add Action Click On Other Actions Find Timers Select The One You Want Count Up Forever or Timer Counting Down. And Then Fill Out The Properties And Then You Are Good

### Checklist

- [X] I've followed all of [the best practices](http://wiki.compilgames.net/doku.php/gdevelop5/extensions/best-practices).
- [X] I confirm that this extension can be integrated to this GitHub repository, distributed and MIT licensed.
- [X] I am aware that the extension may be updated by anyone, and do not need my explicit consent to do so.

### What tier of review do you aim for your extension?

Community (Unreviewed)

### Example file

[My project3.zip](https://github.com/GDevelopApp/GDevelop-extensions/files/10831944/My.project3.zip)

### Extension file

[CountingDownTimers.zip](https://github.com/GDevelopApp/GDevelop-extensions/files/10831948/CountingDownTimers.zip)

**Comment by arthuro555** [comment]
@cubestudioss You never addressed the issues raised by the bot. Are you still willing to submit your extension? Since we did not not hear from you, we'll assume you have abandoned the extension and close the submission. Please follow the bots instructions and create a new submission.
