### ISSUE TITLE
New extension: <Savefile>

### ISSUE THREAD

**Issue by iKaexo** [GDevelopApp/GDevelop-extensions#789]
### Description

The extension  can save a payload variable in a file to load it

The extension have 3 slots to save and load data
The extension have the option to datesave (save file as date)

### How to use the extension

you need to have a global structure variable named "Savestate" with the data you want to save and load

Example:
If you want to load the position of a character you must make a variable in "Savestate", to save the position you must change the position variable and save, then you load and change the position of the character

### Checklist

- [X] I've followed all of [the best practices](http://wiki.compilgames.net/doku.php/gdevelop5/extensions/best-practices).
- [X] I confirm that this extension can be integrated to this GitHub repository, distributed and MIT licensed.
- [X] I am aware that the extension may be updated by anyone, and do not need my explicit consent to do so.

### What tier of review do you aim for your extension?

Community (Unreviewed)

### Example file

[SavefileExtensionExample.zip](https://github.com/GDevelopApp/GDevelop-extensions/files/10873896/SavefileExtensionExample.zip)

### Extension file

[Savefile.zip](https://github.com/GDevelopApp/GDevelop-extensions/files/10873898/Savefile.zip)

**Comment by arthuro555** [comment]
@iKaexo You never addressed the issues raised by the bot. Are you still willing to submit your extension? Since we did not not hear from you, we'll assume you have abandoned the extension and close the submission. Please follow the bots instructions and create a new submission.
