### ISSUE TITLE
New extension: is clicked

### ISSUE THREAD

**Issue by Iwertyuiop123653** [GDevelopApp/GDevelop-extensions#837]
### Description

if you click it allows you to do something

### How to use the extension

yes

### Checklist

- [X] I've followed all of [the best practices](http://wiki.compilgames.net/doku.php/gdevelop5/extensions/best-practices).
- [X] I confirm that this extension can be integrated to this GitHub repository, distributed and MIT licensed.
- [X] I am aware that the extension may be updated by anyone, and do not need my explicit consent to do so.

### What tier of review do you aim for your extension?

Community (Unreviewed)

### Example file

[My project5.zip](https://github.com/GDevelopApp/GDevelop-extensions/files/11095832/My.project5.zip)

### Extension file

[IsClicked.zip](https://github.com/GDevelopApp/GDevelop-extensions/files/11095833/IsClicked.zip)

**Comment by tristanbob** [comment]
Thank you for submitting an extension!

However, this functionality is already available in a few extensions, my favorite beibf the ButtonFSM. 

Please continue thinking of new ideas and submitting them.
