### ISSUE TITLE
[MousePointerLock] Cursor not locking on Linux

### ISSUE THREAD

**Issue by dotPixelx** [GDevelopApp/GDevelop-extensions#928]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/GDevelopApp/GDevelop-extensions/issues)

### Enter the name of the extension

MousePointerLock

### Describe the bug of the extension

Cursor won't lock in place on Linux in editor or desktop build.  Will work in browser.  Unsure if bug occurs on other operating systems.

### Steps to reproduce

Install extension directly within editor
Add to project
Run preview and attempt to lock cursor

### GDevelop platform

Desktop

### GDevelop version

GDevelop version 5.2.165 Flatpak    Extension version 0.1.4

### Platform info

<details>

*OS (e.g. Windows, Linux, macOS, Android, iOS)*
>Linux

*OS Version (e.g. Windows 10, macOS 10.15)*
>Pop!OS 22.04

*Browser(For Web) (e.g. Chrome, Firefox, Safari)*
>Bug doesn't occur in browser

*Device(For Mobile) (e.g. iPhone 12, Samsung Galaxy S21)*
>

</details>

### Additional context

I'm able to fix this issue by editing the extension, going to function "RequestPointerLock"  editing line 2  and deleting " { unadjustedMovement: true } "  But by default, the extension doesn't function correctly.  Unsure if this issue occurs on other OSes/Distros

**Comment by 4ian** [comment]
Should be fixed by https://github.com/GDevelopApp/GDevelop-extensions/pull/1385
