### ISSUE TITLE
New extension: 3D FPS Character

### ISSUE THREAD

**Issue by sg631** [GDevelopApp/GDevelop-extensions#942]
### Description

This adds a behavior to make a 3D Object the FPS Character Controller.

### Checklist

- [X] I've followed all of [the best practices](http://wiki.compilgames.net/doku.php/gdevelop5/extensions/best-practices).
- [X] I confirm that this extension can be integrated to this GitHub repository, distributed and MIT licensed.
- [X] I am aware that the extension may be updated by anyone, and do not need my explicit consent to do so.

### What tier of review do you aim for your extension?

Community (Unreviewed)

### Example file

[example.zip](https://github.com/GDevelopApp/GDevelop-extensions/files/12090786/example.zip)

### Extension file

[ThreeDimensionsPlatforming.zip](https://github.com/GDevelopApp/GDevelop-extensions/files/12090814/ThreeDimensionsPlatforming.zip)

**Comment by arthuro555** [comment]
@sg631 You never addressed the issues raised by the bot. Are you still willing to submit your extension? Since we did not not hear from you, we'll assume you have abandoned the extension and close the submission. Please follow the bots instructions and create a new submission.

**Comment by sg631** [comment]
Sorry I accidentally created a second post instead of updating this one. [Link](https://github.com/GDevelopApp/GDevelop-extensions/issues/942)
