### ISSUE TITLE
[slice an object into pieces] delete object after slice, in the extension graph, misspelt causing no deletion

### ISSUE THREAD

**Issue by player-toaster** [GDevelopApp/GDevelop-extensions#950]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/GDevelopApp/GDevelop-extensions/issues)

### Enter the name of the extension

slice an object into pieces

### Describe the bug of the extension

this is how i got it when i installed it
![GDevelop_wF56JEP2DA](https://github.com/GDevelopApp/GDevelop-extensions/assets/112227150/e1f75ca3-87eb-4ad4-b19c-aaa8e1f8d324)

to fix:
![GDevelop_Pquji3oyvq](https://github.com/GDevelopApp/GDevelop-extensions/assets/112227150/9859f598-9517-4e89-91b7-7bc3f4944729)

this is how it should be:
![GDevelop_sEVqFQNMu3](https://github.com/GDevelopApp/GDevelop-extensions/assets/112227150/a5a1f432-1c0e-461a-b629-dae8bb7f1cf4)

### Steps to reproduce

i installed it and it was like this, and so it should always be produced

### GDevelop platform

Desktop

### GDevelop version

5.2.167

**Comment by tristanbob** [comment]
Fixed by: https://github.com/GDevelopApp/GDevelop-extensions/pull/959

@player-toaster thank you so much for finding this bug, and also for providing the fix!  
This community really appreciates people like you who help us improve GDevelop.  Thanks again!
