### ISSUE TITLE
New extension: Wheel Joint Creator

### ISSUE THREAD

**Issue by bigheadbrogames** [GDevelopApp/GDevelop-extensions#967]
### Description

Create Wheels Joints for a two wheeled vehicle or any transport:
1-cars; 2-bikes;3-trucks with 2 axes.
That's it.

### How to use the extension

Create 3 sprite objects.
One for car/vehicle and two others for front and back wheels.
Add Physcis behavior for these objects.
At Events, add a Beginning of the Scene condition and this extension only action.
Follow the fields and fill them with the respective values. 

### Checklist

- [X] I've followed all of [the best practices](http://wiki.compilgames.net/doku.php/gdevelop5/extensions/best-practices).
- [X] I confirm that this extension can be integrated to this GitHub repository, distributed and MIT licensed.
- [X] I am aware that the extension may be updated by anyone, and do not need my explicit consent to do so.

### What tier of review do you aim for your extension?

Community (Unreviewed)

### Example file

[VEHICLE JOINT CREATOR.zip](https://github.com/GDevelopApp/GDevelop-extensions/files/12330412/VEHICLE.JOINT.CREATOR.zip)

### Extension file

[WheelJointCreator.zip](https://github.com/GDevelopApp/GDevelop-extensions/files/12330415/WheelJointCreator.zip)

**Comment by tristanbob** [comment]
Duplicate of #966.  Please update that issue to continue this extension.

**Comment by bigheadbrogames** [comment]
No need to continue.
Just try to contribute, but I understand that is not good enough.

Thanks,

Guilherme Bastos

Em sáb., 23 de set. de 2023 às 00:17, Tristan Rhodes <
***@***.***> escreveu:
