### ISSUE TITLE
New extension: One Signal Notification

### ISSUE THREAD

**Issue by TheGemDev** [GDevelopApp/GDevelop-extensions#988]
### Description

Send push Android/IOS notifications via one signal 

### How to use the extension

Make use of the initialize one signal action

![image](https://github.com/GDevelopApp/GDevelop-extensions/assets/53819287/0621f78c-cac0-486c-92d4-3534899e93e9)

go to https://onesignal.com to create an account.

Follow these steps to generate a Google server API key
https://documentation.onesignal.com/docs/generate-a-google-server-api-key

### Checklist

- [X] I've followed all of [the best practices](http://wiki.compilgames.net/doku.php/gdevelop5/extensions/best-practices).
- [X] I confirm that this extension can be integrated to this GitHub repository, distributed and MIT licensed.
- [X] I am aware that the extension may be updated by anyone, and do not need my explicit consent to do so.

### What tier of review do you aim for your extension?

Community (Unreviewed)

### Example file

[msg.zip](https://github.com/GDevelopApp/GDevelop-extensions/files/12446533/msg.zip)

### Extension file

[OneSignal.zip](https://github.com/GDevelopApp/GDevelop-extensions/files/12446656/OneSignal.zip)

**Comment by TheGemDev** [comment]
[OneSignal.zip](https://github.com/GDevelopApp/GDevelop-extensions/files/12446656/OneSignal.zip)

**Comment by ElRamo** [comment]
Hello,
Thank you for your amazing contribution.
I am trying to integrate the extension but somehow I am not able to register new subscribers.
I followed the guide bellow
[OneSignal Documentation](https://documentation.onesignal.com/docs/generate-firebase-credentials)
[Android: Firebase Credentials](https://documentation.onesignal.com/docs/generate-firebase-credentials)

Directions on how to generate a Firebase Cloud Messaging API Credentials for sending Android App Notifications

1/ Activate Firebase Cloud Messaging API (V1)
2/ Generate a Private Key JSON file (Node.js)
3/ Activate the platform Google Android (FCM) in OneSignal (In the part “Select SDK” I tried both Native android and Cordova)
4/ Download and import the extention in Gdevelop ([Onesignal GDevelop Extension · GitHub](https://gist.github.com/TheGemDev/4e2d65d4ee041ab0385cb4681faa5847))
5/ Integrate it as follow :
Beginning of the first scene >

    Request Notification Permission : TRUE
    Initialize Onesignal (My app ID + user must consent TRUE)
    I tried the application using mobile manual build and mobile One-click packaging. I tested the .apk in a real phone and in android studio virtual devices (with playstore installed).
    I checked, the notification is allowed.
    But still, when I launch the application no new subscriber is registered in OneSignal.
    Thank you in advance for your precious time.
