### ISSUE TITLE
New extension: <title>platform 3d camera

### ISSUE THREAD

**Issue by Boy1developer** [GDevelopApp/GDevelop-extensions#990]
### Description

I make special 3d view  camera and you can edit it easy from extension editor 

### How to use the extension

the extension  about 1 behavior to make the camera

### Checklist

- [X] I've followed all of [the best practices](http://wiki.compilgames.net/doku.php/gdevelop5/extensions/best-practices).
- [X] I confirm that this extension can be integrated to this GitHub repository, distributed and MIT licensed.
- [X] I am aware that the extension may be updated by anyone, and do not need my explicit consent to do so.

### What tier of review do you aim for your extension?

Community (Unreviewed)

### Example file

[3d game.zip](https://github.com/GDevelopApp/GDevelop-extensions/files/12446799/3d.game.zip)

### Extension file

![bandicam 2023-08-27 01-03-59-715](https://github.com/GDevelopApp/GDevelop-extensions/assets/143229293/f9317135-254b-43fc-a233-491c7b23b374)
![bandicam 2023-08-27 01-04-27-518](https://github.com/GDevelopApp/GDevelop-extensions/assets/143229293/96cb50ef-6aac-4c2d-82ca-bbc4985c75d1)

**Comment by arthuro555** [comment]
Closing as duplicate from #1000
