### ISSUE TITLE
platform 3d camera

### ISSUE THREAD

**Issue by Boy1developer** [GDevelopApp/GDevelop-extensions#991]
### Description

make camera follow the object from z x and Y axis with special view

### How to use the extension

if you but a behaviour will add new action to the object to change the distance between the object and camera

### Checklist

- [X] I've followed all of [the best practices](http://wiki.compilgames.net/doku.php/gdevelop5/extensions/best-practices).
- [X] I confirm that this extension can be integrated to this GitHub repository, distributed and MIT licensed.
- [X] I am aware that the extension may be updated by anyone, and do not need my explicit consent to do so.

### What tier of review do you aim for your extension?

Reviewed

### Example file

[3d game.zip](https://github.com/GDevelopApp/GDevelop-extensions/files/12447477/3d.game.zip)

### Extension file

[platform3dCamera.zip](https://github.com/GDevelopApp/GDevelop-extensions/files/12447480/platform3dCamera.zip)

**Comment by arthuro555** [comment]
Closing as duplicate from #1000
